export type Lang = "en" | "lt";

export const en = {
  nav: {
    product: "Product",
    approach: "Approach",
    who: "Who it's for",
    blog: "Blog",
    faq: "FAQ",
    cta: "Request a demo",
    langLabel: "Language",
    skip: "Skip to content",
    home: "Home",
  },
  hero: {
    eyebrow: "PROPERTY MANAGEMENT SYSTEM WITH YOUR OWN BOOKING WEBSITE\n\n",
    h1: "Software that *fits* the way your property already works",
    sub: "Hotels, cabins, guesthouses and apartments each run differently — and none of them run the way the software they were sold assumes. Revoo is a platform we shape to your operation, with a booking website that is genuinely yours.",
    primary: "Request a demo",
    secondary: "See how it works",
    status: "Write to us, and we’ll give you access to try it out today.",
  },
  carousel: {
    label: "Product screens",
    prev: "Previous slide",
    next: "Next slide",
    goTo: "Go to slide",
    slides: [
      "Move a booking. Everything else follows.",
      "Today's work, already sorted by urgency.",
      "Invoices ready before the guest has left.",
      "Your whole operation, on the way to work.",
      "The whole week, before it starts.",
    ],
  },
  approach: {
    eyebrow: "Our approach",
    h2: "Configuration is not *customisation*",
    lede: "Your property, chosen by your guests, has its own face. Our job is to make the system show it, not hide it under a template.",
    cardA: {
      title: "Our team's support",
      body: "We look at how your property actually operates — what you sell in addition to the rented room, who you issue invoices to, how your team works — and launch the system together with you, which we constantly supervise.",
    },
    cardB: {
      title: "It costs more than a subscription",
      body: "In return, you get a system that does not require adapting to it and a website with a booking system that is actually yours.",
    },
  },
  week: {
    eyebrow: "The week",
    h2: "Your whole month, on one *screen*",
    lede: "Units down the side, days across the top. Drag a booking to another unit or another week and it just moves.",
    points: [
      "Double bookings are refused before you make one — not discovered when the guest is standing at the door.",
      "Same-day turnovers are allowed on purpose: one guest out, the next one in, same date.",
      "Click an empty cell to create a booking already filled in with the unit and the dates.",
      "Availability imported from Booking.com and Airbnb sits in the same view, marked as external.",
    ],
  },
  morning: {
    eyebrow: "The morning",
    h2: "Your team knows what to do before you *ask*",
    lede: "Revoo reads today's bookings and works out what each unit actually needs, then sorts the list by urgency. Nobody briefs anybody.",
    points: [
      "Same-day turnovers come first — the narrowest window in the day, and the one that goes wrong most often.",
      "A unit that didn't get finished does not quietly vanish from tomorrow's list.",
      "Ordered extras appear as a preparation checklist, so nothing is discovered at check-in.",
      "Faults are reported in one tap and land in the manager's view instantly.",
      "Cleaners never see guest contacts, prices or payment status. Only the work.",
    ],
  },
  paperwork: {
    eyebrow: "The paperwork",
    h2: "The guest checks out. The invoice already *exists*",
    lede: "Sequential numbering, your company details, VAT or non-VAT, ready as a PDF. No spreadsheet, no re-typing, no gaps in the series when the auditor asks.",
    points: [
      "Company guests are first-class: company name, registration number, VAT number and address are captured at booking, not chased afterwards.",
      "Numbers are claimed in strict sequence, so the series never has a hole.",
      "Every paid extra becomes its own line, whatever you sell alongside the room.",
      "Invoicing is set up to your country's rules as part of your implementation.",
    ],
  },
  channel: {
    eyebrow: "Your booking channel",
    h2: "A booking website, not a booking *widget*",
    lede: "Every other system gives you a box to paste into your site. It looks borrowed, because it is. Revoo works the other way around: your website is the booking system — your design, your domain, your words, talking to the same engine your admin panel uses.",
    note: "Under the hood this is a documented REST API with its own keys, origin allowlist and rate limits — so a mobile app, a partner integration or a second booking channel later is a configuration, not a rebuild.",
  },
  segments: {
    eyebrow: "Built for your kind of property",
    h2: "Designed for how *you* operate",
    prev: "Previous property type",
    next: "Next property type",
    goTo: "Show property type",
    slides: [
      {
        title: "Hotels",
        body: "Rooms, rates and a front desk. Revoo gives you the calendar, the housekeeping list and the invoices, without the enterprise price tag or the six-week configuration project that usually comes with them.",
      },
      {
        title: "Cabins",
        body: "Cabins are won and lost on the turnover. Revoo works out which cabins need what today, releases the door code only once the booking is confirmed, and keeps the whole season on one screen.",
      },
      {
        title: "Guesthouses",
        body: "Usually one person doing everything. Bookings, cleaning, guest emails and invoices live in one place, so that one person can occasionally be somewhere else.",
      },
      {
        title: "Apartments",
        body: "Your units are not all in one building, and they do not need to be. Revoo treats every unit as its own property, so apartments scattered across different addresses still run from a single calendar.",
      },
    ],
  },
  ctaBand: {
    text: "Curious whether this fits your property? One 45-minute conversation will tell you.",
    button: "Request a demo",
  },
  included: {
    eyebrow: "What you get",
    h2: "What's in the platform, and what we *build* for you",
    lede: "We would rather be precise than impressive. Here is the honest split.",
    left: {
      title: "In the platform from day one",
      sub: "Working today, in production.",
      items: [
        "Multi-property dashboard with occupancy, revenue and expense figures",
        "Drag-and-drop booking calendar with double-booking prevention",
        "Rate tiers by length of stay, plus paid extras per property",
        "Automated guest emails — confirmation, change, cancellation, pre-arrival reminder, review request — in the guest's own language",
        "Invoice generation with sequential numbering and PDF output",
        "Housekeeping module with automatic work-type detection and a mobile app for cleaning staff",
        "Roles and email invitations for your team",
        "Availability import from Booking.com and Airbnb via iCal",
        "Documented public REST API with keys, origin allowlist and rate limits",
        "Legal document management served straight to your guest site",
      ],
    },
    right: {
      title: "Built into your implementation",
      sub: "Scoped in the first conversation, built for your property.",
      items: [
        "Your booking website — designed for your property, on your domain",
        "Payments — we connect the provider you actually use",
        "Invoicing to your country's rules — the identifiers, rates and numbering your tax authority expects",
        "Your languages, in the interface and in guest emails",
        "The channel connections your property actually needs",
        "Whatever you sell alongside the room",
        "Migration of your existing bookings, and setup of units, rates and policies",
        "Training for your team, in their language",
      ],
    },
  },
  fit: {
    eyebrow: "Fit",
    h2: "Who this is for — and who it *isn't*",
    lede: "Saying this out loud saves us both a call.",
    yesTitle: "This is for you if",
    noTitle: "This is not for you if",
    yes: [
      "6–30 units, owner-operated or run by a small team",
      "Hotels, cabins, guesthouses, or apartments across several addresses",
      "You sell more than the room, whatever that is at your property",
      "Business guests who need a proper invoice to a company",
      "A cleaning team currently coordinated by phone, paper or WhatsApp",
      "Too much of your revenue goes to OTA commission",
      "You want a website that looks like your property, not like software",
    ],
    no: [
      "A single property run as a side income rather than a business",
      "Chains and groups above roughly 50 units",
      "You need full two-way channel management across many OTAs on day one",
      "You want to sign up online tonight and configure it yourself — we don't work that way",
    ],
  },
  start: {
    eyebrow: "Getting started",
    h2: "How it actually *starts*",
    lede: "No credit card form, and no 14-day trial you would abandon on day three.",
    steps: [
      {
        title: "A conversation",
        body: "About 45 minutes. How your property runs, what you sell alongside the room, what breaks today, and what your invoices have to look like. We tell you honestly whether we are a fit.",
      },
      {
        title: "Implementation",
        body: "We set up your units, rates, extras and policies, build your booking website, connect your payment provider and adapt invoicing to your country. You review it as it takes shape.",
      },
      {
        title: "Launch",
        body: "Your existing bookings move across. We train reception and housekeeping in their own language. Then we stay close through the first season.",
      },
    ],
    cta: "Request a demo",
  },
  demo: {
    eyebrow: "Talk to us",
    h2: "Let's look at your *property*",
    lede: "Tell us a little about it and we will come back within one working day — with either a demo time or an honest \u201Cwe are not the right fit\u201D.",
    facts: [
      "hello@revoo.site",
      "Working in English and Lithuanian",
      "Based in Lithuania · onboarding properties in Iceland",
    ],
    form: {
      name: "Name",
      email: "Email",
      property: "Property name",
      country: "Country",
      countries: ["Iceland", "Lithuania", "Latvia", "Estonia", "Norway", "Germany", "Other"],
      type: "Property type",
      types: ["Hotel", "Cabins", "Guesthouse", "Apartments", "Other"],
      units: "Number of units",
      unitOptions: ["1–5", "6–15", "16–30", "31–50", "50+"],
      current: "What you use today",
      currentOptions: [
        "Spreadsheet or paper",
        "Booking.com extranet only",
        "Another PMS",
        "A booking widget on our website",
        "Other",
      ],
      notes: "Anything else we should know?",
      optional: "optional",
      required: "required",
      submit: "Request a demo",
      fineprint: "We reply within one working day. No automated sequences.",
      select: "Select",
    },
    success: {
      title: "Thank you",
      body: "We will be in touch within one working day.",
    },
  },
  faq: {
    eyebrow: "Questions",
    h2: "The things people actually *ask*",
    items: [
      {
        q: "What does it cost?",
        a: "There is a one-off implementation fee and a monthly subscription. The implementation fee depends on scope — how many units, what you sell alongside the room, whether you need a new website, which payment provider, which country's invoicing. We quote after the first conversation rather than before it, because a number quoted blind would be wrong in one direction or the other.",
      },
      {
        q: "Do you handle payments?",
        a: "We connect the payment provider you actually use as part of your implementation. It is not a checkbox on a settings page — it is scoped and built for your setup, which also means it works with the acquirer you already have a contract with.",
      },
      {
        q: "Does it sync with Booking.com and Airbnb?",
        a: "Availability import over iCal works today, so external bookings appear in your calendar and block the unit. Deeper channel connections are scoped as part of an implementation when a property needs them. We are deliberately not claiming to be a 200-channel channel manager — if that is what you need on day one, a large platform will serve you better, and we will say so.",
      },
      {
        q: "Can I keep my current website?",
        a: "Yes — it can connect to Revoo through the public API. But if your current site cannot take a booking without sending the guest somewhere else, replacing it is usually the single change that pays for the whole project.",
      },
      {
        q: "Why isn't there a sign-up button?",
        a: "Because every property we have set up has needed something the previous one did not. A self-service sign-up would hand you an empty dashboard and a settings page, and you would be doing the implementation yourself. We would rather do it properly.",
      },
      {
        q: "What happens if I outgrow you?",
        a: "The platform is API-first and your data is yours — properties, bookings, guests and invoices, all exportable. We would rather you left cleanly than felt locked in.",
      },
      {
        q: "Where are you based?",
        a: "Lithuania. The platform runs in production today, and we are onboarding properties in Iceland. We work in English and Lithuanian.",
      },
    ],
  },
  footer: {
    tagline:
      "A property management system and a booking website for independent hotels, cabins, guesthouses and apartments.",
    linksTitle: "Site",
    langTitle: "Language",
    rights: "© 2026 Revoo",
    contact: "revoo.site · hello@revoo.site",
  },
  blog: {
    title: "Blog",
    eyebrow: "Writing",
    h2: "Notes on running a small *property*",
    lede: "Practical writing about booking, invoicing and the operational day — for independent hotels, cabins, guesthouses and apartments.",
    readingTime: "min read",
    back: "Back to the blog",
    metaTitle: "Revoo blog — booking, invoicing and running a small property",
    metaDescription:
      "Practical articles for independent hotels, cabins, guesthouses and apartments: choosing a property management system, invoicing rules, housekeeping and direct bookings.",
    disclaimer:
      "This article is general information, not tax or legal advice. Check specifics with your accountant or your national tax authority.",
    ctaTitle: "Wondering whether Revoo fits your property?",
    ctaBody: "One 45-minute conversation, and an honest answer either way.",
    ctaButton: "Request a demo",
  },
  notFound: {
    title: "Page not found",
    body: "This address does not exist, or it has moved.",
    cta: "Back to the homepage",
  },
  media: {
    missing: "Media file not available",
    browserUrl: "app.revoo.site",
    alt: {
      calendar: "Revoo booking calendar: units in rows, days in columns, bookings dragged between units",
      housekeepingApp: "Revoo housekeeping app on a phone, showing today's rooms sorted by urgency",
      housekeepingWeek: "Revoo weekly housekeeping table with work types for each room",
      invoice: "A VAT invoice generated by Revoo, ready as a PDF",
      bookingSite: "A booking website built with Revoo, showing availability and prices for chosen dates",
    },
  },
  mobileCta: {
    text: "Request a demo",
    dismiss: "Hide this bar",
  },
};

export const lt: typeof en = {
  nav: {
    product: "Produktas",
    approach: "Požiūris",
    who: "Kam skirta",
    blog: "Blogas",
    faq: "DUK",
    cta: "Užsisakyti demo",
    langLabel: "Kalba",
    skip: "Pereiti prie turinio",
    home: "Pradžia",
  },
  hero: {
    eyebrow: "APGYVENDINIMO VALDYMO SISTEMA SU JŪSŲ REZERVACIJŲ SVETAINE\n\n",
    h1: "Sistema, kuri *prisitaiko* prie jūsų objekto",
    sub: "Viešbučiai, nameliai, svečių namai ir apartamentai dirba skirtingai — ir nė vienas iš jų nedirba taip, kaip numano jiems parduota programa. Revoo yra platforma, kurią pritaikome jūsų veiklai, kartu su rezervacijų svetaine, kuri iš tikrųjų yra jūsų.",
    primary: "Užsisakyti demo",
    secondary: "Kaip tai veikia",
    status: "Parašykite mums ir suteiksime prieigą išbandyti jau šiandien.",
  },
  carousel: {
    label: "Produkto vaizdai",
    prev: "Ankstesnė skaidrė",
    next: "Kita skaidrė",
    goTo: "Rodyti skaidrę",
    slides: [
      "Perkelkite rezervaciją. Visa kita seka paskui.",
      "Šios dienos darbai, jau surikiuoti pagal skubumą.",
      "Sąskaitos paruoštos dar svečiui neišvykus.",
      "Visa veikla — pakeliui į darbą.",
      "Visa savaitė, dar jai neprasidėjus.",
    ],
  },
  approach: {
    eyebrow: "Mūsų požiūris",
    h2: "Konfigūracija nėra *pritaikymas*",
    lede: "Jūsų objektas, kurį renkasi jūsų klientai, turi savo veidą. Mūsų darbas — kad sistema jį parodytų, o ne paslėptų po šablonu.",
    cardA: {
      title: "Mūsų komandos palaikymas",
      body: "Pažiūrime, kaip jūsų objektas realiai veikia — ką parduodate papildomai prie išnuomoto kambario, kam išrašote sąskaitas, kaip jūsų komanda dirba — ir sistemą paleidžiame kartu su jumis, kurią nuolatos prižiūrime.",
    },
    cardB: {
      title: "Tai kainuoja daugiau nei prenumerata",
      body: "Mainais gaunate sistemą, kuri nereikalauja prisitaikyti prie jos ir svetainę su rezervacijos sistema, kuri iš tikrųjų yra jūsų.",
    },
  },
  week: {
    eyebrow: "Savaitė",
    h2: "Visas mėnuo *viename* ekrane",
    lede: "Vienetai eilutėse, dienos stulpeliuose. Nutempkite rezervaciją į kitą vienetą ar kitą savaitę — ir ji tiesiog persikelia.",
    points: [
      "Dviguba rezervacija atmetama dar prieš ją padarant — ne tada, kai svečias jau stovi prie durų.",
      "Tos pačios dienos apyvarta leidžiama sąmoningai: vienas išvyksta, kitas atvyksta tą pačią dieną.",
      "Spustelėjus tuščią langelį atsidaro rezervacija, jau užpildyta vienetu ir datomis.",
      "Užimtumas, importuotas iš Booking.com ir Airbnb, matomas tame pačiame vaizde ir pažymėtas kaip išorinis.",
    ],
  },
  morning: {
    eyebrow: "Rytas",
    h2: "Komanda žino, ką daryti, dar jums *nepaklausus*",
    lede: "Revoo perskaito šios dienos rezervacijas, nustato, ko kiekvienam vienetui realiai reikia, ir surikiuoja sąrašą pagal skubumą. Niekas niekam nieko neaiškina.",
    points: [
      "Tos pačios dienos apyvartos rodomos pirmos — siauriausias dienos langas ir tas, kuris dažniausiai sugriūva.",
      "Nesutvarkytas vienetas nedingsta tyliai iš rytojaus sąrašo.",
      "Užsakytos papildomos paslaugos rodomos kaip paruošimo atmintinė, todėl niekas nepaaiškėja tik svečiui atvykus.",
      "Gedimas pranešamas vienu paspaudimu ir iš karto matomas administratorei.",
      "Kambarinės nemato svečių kontaktų, kainų ir mokėjimo būsenos. Tik darbą.",
    ],
  },
  paperwork: {
    eyebrow: "Popierizmas",
    h2: "Svečias išvyko. Sąskaita jau *yra*",
    lede: "Nuosekli numeracija, jūsų rekvizitai, su PVM arba be, paruošta PDF. Jokių lentelių, jokio perrašinėjimo ir jokių spragų serijoje, kai paklausia auditorius.",
    points: [
      "Verslo klientai — ne priedas: įmonės pavadinimas, kodas, PVM kodas ir adresas surenkami rezervuojant, o ne vaikomasi paskui.",
      "Numeriai priskiriami griežta seka, todėl serijoje niekada nelieka skylės.",
      "Kiekviena apmokėta papildoma paslauga tampa atskira eilute — kad ir ką parduotumėte šalia kambario.",
      "Sąskaitos pritaikomos jūsų šalies taisyklėms kaip diegimo dalis.",
    ],
  },
  channel: {
    eyebrow: "Jūsų rezervacijų kanalas",
    h2: "Rezervacijų svetainė, o ne rezervacijų *langelis*",
    lede: "Visos kitos sistemos duoda langelį, kurį įklijuojate į savo svetainę. Jis atrodo svetimas, nes toks ir yra. Revoo veikia atvirkščiai: jūsų svetainė ir yra rezervacijų sistema — jūsų dizainas, jūsų domenas, jūsų žodžiai, kalbantys su tuo pačiu varikliu kaip ir jūsų administravimo skydelis.",
    note: "Po gaubtu tai yra dokumentuotas REST API su savo raktais, domenų sąrašu ir užklausų ribojimu — todėl mobilioji programėlė, partnerio integracija ar antras rezervacijų kanalas vėliau yra konfigūracija, o ne perdarymas iš naujo.",
  },
  segments: {
    eyebrow: "Sukurta jūsų objekto tipui",
    h2: "Pritaikyta tam, kaip *jūs* dirbate",
    prev: "Ankstesnis objekto tipas",
    next: "Kitas objekto tipas",
    goTo: "Rodyti objekto tipą",
    slides: [
      {
        title: "Viešbučiai",
        body: "Kambariai, kainos ir registratūra. Revoo duoda kalendorių, kambarinių sąrašą ir sąskaitas — be įmonėms skirtos kainos ir be šešių savaičių konfigūravimo projekto, kuris paprastai prie jų prisideda.",
      },
      {
        title: "Nameliai",
        body: "Nameliai laimimi ir pralaimimi ties apyvarta. Revoo nustato, kuriam nameliui ko šiandien reikia, durų kodą išsiunčia tik patvirtinus rezervaciją, ir laiko visą sezoną viename ekrane.",
      },
      {
        title: "Svečių namai",
        body: "Paprastai vienas žmogus daro viską. Rezervacijos, tvarkymas, laiškai svečiams ir sąskaitos gyvena vienoje vietoje, kad tas vienas žmogus kartais galėtų būti kitur.",
      },
      {
        title: "Apartamentai",
        body: "Jūsų vienetai nebūtinai yra viename pastate — ir neturi būti. Revoo kiekvieną vienetą traktuoja kaip atskirą objektą, todėl skirtingais adresais išsibarstę apartamentai valdomi iš vieno kalendoriaus.",
      },
    ],
  },
  ctaBand: {
    text: "Įdomu, ar tai tinka jūsų objektui? Vienas 45 minučių pokalbis atsakys.",
    button: "Užsisakyti demo",
  },
  included: {
    eyebrow: "Ką gaunate",
    h2: "Kas yra platformoje ir ką *sukuriame* jums",
    lede: "Verčiau būsime tikslūs nei įspūdingi. Štai sąžiningas padalijimas.",
    left: {
      title: "Platformoje nuo pirmos dienos",
      sub: "Veikia šiandien, realiai.",
      items: [
        "Kelių objektų skydelis su užimtumo, pajamų ir išlaidų rodikliais",
        "Velkamas rezervacijų kalendorius su dvigubų rezervacijų prevencija",
        "Kainų pakopos pagal naktų skaičių ir apmokamos papildomos paslaugos",
        "Automatiniai laiškai svečiui — patvirtinimas, pakeitimas, atšaukimas, priminimas prieš atvykimą, atsiliepimo prašymas — svečio kalba",
        "Sąskaitų generavimas su nuoseklia numeracija ir PDF",
        "Kambarių tvarkymo modulis su automatiniu darbo tipo nustatymu ir mobilia programėle personalui",
        "Rolės ir kvietimai el. paštu jūsų komandai",
        "Užimtumo importas iš Booking.com ir Airbnb per iCal",
        "Dokumentuotas viešas REST API su raktais, domenų sąrašu ir ribojimais",
        "Teisinių dokumentų valdymas, tiekiamas tiesiai į svečių svetainę",
      ],
    },
    right: {
      title: "Sukuriama jūsų diegimo metu",
      sub: "Apibrėžiama per pirmą pokalbį, statoma pagal jūsų objektą.",
      items: [
        "Jūsų rezervacijų svetainė — sukurta jūsų objektui, jūsų domene",
        "Mokėjimai — prijungiame tą sprendimą, kurį realiai naudojate",
        "Sąskaitos pagal jūsų šalies taisykles — identifikatoriai, tarifai ir numeracija, kurių tikisi mokesčių administratorius",
        "Jūsų kalbos — sąsajoje ir laiškuose svečiams",
        "Tos kanalų jungtys, kurių jūsų objektui realiai reikia",
        "Kad ir ką parduotumėte šalia kambario",
        "Esamų rezervacijų perkėlimas, vienetų, kainų ir taisyklių sukonfigūravimas",
        "Komandos mokymai jų kalba",
      ],
    },
  },
  fit: {
    eyebrow: "Kam skirta",
    h2: "Kam tai tinka — ir kam *netinka*",
    lede: "Pasakius tai garsiai, abu sutaupome skambutį.",
    yesTitle: "Tinka, jei",
    noTitle: "Netinka, jei",
    yes: [
      "6–30 vienetų, valdoma savininko arba mažos komandos",
      "Viešbučiai, nameliai, svečių namai arba apartamentai keliais adresais",
      "Parduodate ne tik kambarį — kad ir kas tai būtų jūsų objekte",
      "Verslo klientai, kuriems reikia tikros sąskaitos įmonei",
      "Tvarkymo komanda, šiuo metu derinama telefonu, popieriuje ar per WhatsApp",
      "Per didelė pajamų dalis atitenka OTA komisiniams",
      "Norite svetainės, kuri atrodo kaip jūsų objektas, o ne kaip programa",
    ],
    no: [
      "Vienas objektas, valdomas kaip papildomos pajamos, o ne kaip verslas",
      "Tinklai ir grupės virš maždaug 50 vienetų",
      "Nuo pirmos dienos reikia pilno dvipusio kanalų valdymo per daug OTA",
      "Norite užsiregistruoti šįvakar internetu ir susikonfigūruoti patys — mes taip nedirbame",
    ],
  },
  start: {
    eyebrow: "Kaip pradėti",
    h2: "Kaip tai iš tikrųjų *prasideda*",
    lede: "Jokios kortelės formos ir jokio 14 dienų bandymo, kurį mestumėte trečią dieną.",
    steps: [
      {
        title: "Pokalbis",
        body: "Apie 45 minutes. Kaip veikia jūsų objektas, ką parduodate šalia kambario, kas šiandien lūžta ir kaip turi atrodyti jūsų sąskaitos. Sąžiningai pasakome, ar tinkame vieni kitiems.",
      },
      {
        title: "Diegimas",
        body: "Sukonfigūruojame vienetus, kainas, papildomas paslaugas ir taisykles, sukuriame rezervacijų svetainę, prijungiame mokėjimų sprendimą ir pritaikome sąskaitas jūsų šaliai. Peržiūrite tai, kol darome.",
      },
      {
        title: "Paleidimas",
        body: "Esamos rezervacijos persikelia. Apmokome registratūrą ir kambarines jų kalba. Tada liekame šalia visą pirmą sezoną.",
      },
    ],
    cta: "Užsisakyti demo",
  },
  demo: {
    eyebrow: "Susisiekime",
    h2: "Pažiūrėkime į jūsų *objektą*",
    lede: "Papasakokite apie jį truputį, ir per vieną darbo dieną grįšime arba su demo laiku, arba su sąžiningu \u201Emes jums netinkame\u201C.",
    facts: [
      "hello@revoo.site",
      "Dirbame anglų ir lietuvių kalbomis",
      "Įsikūrę Lietuvoje · pradedame dirbti su objektais Islandijoje",
    ],
    form: {
      name: "Vardas",
      email: "El. paštas",
      property: "Objekto pavadinimas",
      country: "Šalis",
      countries: ["Islandija", "Lietuva", "Latvija", "Estija", "Norvegija", "Vokietija", "Kita"],
      type: "Objekto tipas",
      types: ["Viešbutis", "Nameliai", "Svečių namai", "Apartamentai", "Kita"],
      units: "Vienetų skaičius",
      unitOptions: ["1–5", "6–15", "16–30", "31–50", "50+"],
      current: "Ką naudojate šiandien",
      currentOptions: [
        "Lentelė ar popierius",
        "Tik Booking.com extranet",
        "Kita PMS",
        "Rezervacijų langelis svetainėje",
        "Kita",
      ],
      notes: "Ką dar turėtume žinoti?",
      optional: "neprivaloma",
      required: "privaloma",
      submit: "Užsisakyti demo",
      fineprint: "Atsakome per vieną darbo dieną. Jokių automatinių sekų.",
      select: "Pasirinkite",
    },
    success: {
      title: "Ačiū",
      body: "Susisieksime per vieną darbo dieną.",
    },
  },
  faq: {
    eyebrow: "Klausimai",
    h2: "Ką žmonės iš tikrųjų *klausia*",
    items: [
      {
        q: "Kiek tai kainuoja?",
        a: "Yra vienkartinis diegimo mokestis ir mėnesinė prenumerata. Diegimo mokestis priklauso nuo apimties — kiek vienetų, ką parduodate šalia kambario, ar reikia naujos svetainės, koks mokėjimų sprendimas, kurios šalies sąskaitos. Kainą pasakome po pirmo pokalbio, o ne prieš jį, nes akla kaina būtų neteisinga viena ar kita kryptimi.",
      },
      {
        q: "Ar tvarkote mokėjimus?",
        a: "Diegimo metu prijungiame tą mokėjimų sprendimą, kurį realiai naudojate. Tai nėra varnelė nustatymuose — tai apibrėžiama ir sukuriama jūsų atvejui, todėl veikia su ta įstaiga, su kuria jau turite sutartį.",
      },
      {
        q: "Ar sinchronizuojasi su Booking.com ir Airbnb?",
        a: "Užimtumo importas per iCal veikia šiandien, todėl išorinės rezervacijos matomos kalendoriuje ir užima vienetą. Gilesnės kanalų jungtys apibrėžiamos kaip diegimo dalis, kai objektui to reikia. Sąmoningai neteigiame, kad esame 200 kanalų channel manager — jei to reikia nuo pirmos dienos, didelė platforma jums tiks geriau, ir mes tai pasakysime.",
      },
      {
        q: "Ar galiu pasilikti dabartinę svetainę?",
        a: "Taip — ji gali jungtis prie Revoo per viešą API. Bet jei dabartinė svetainė negali priimti rezervacijos nenusiųsdama svečio kitur, jos pakeitimas paprastai yra tas vienas pokytis, kuris atsiperka už visą projektą.",
      },
      {
        q: "Kodėl nėra registracijos mygtuko?",
        a: "Nes kiekvienam objektui, kurį diegėme, reikėjo kažko, ko nereikėjo ankstesniam. Savitarnos registracija paduotų jums tuščią skydelį ir nustatymų puslapį, o diegimą darytumėte patys. Mes verčiau padarysime tai kaip reikia.",
      },
      {
        q: "Kas bus, jei jus peraugsiu?",
        a: "Platforma sukurta pagal API-first principą, o duomenys yra jūsų — objektai, rezervacijos, svečiai ir sąskaitos, viskas eksportuojama. Verčiau išeisite tvarkingai, nei jausitės įstrigę.",
      },
      {
        q: "Kur esate įsikūrę?",
        a: "Lietuvoje. Platforma šiandien veikia realiai, ir pradedame dirbti su objektais Islandijoje. Dirbame anglų ir lietuvių kalbomis.",
      },
    ],
  },
  footer: {
    tagline:
      "Apgyvendinimo valdymo sistema ir rezervacijų svetainė nepriklausomiems viešbučiams, nameliams, svečių namams ir apartamentams.",
    linksTitle: "Svetainė",
    langTitle: "Kalba",
    rights: "© 2026 Revoo",
    contact: "revoo.site · hello@revoo.site",
  },
  blog: {
    title: "Blogas",
    eyebrow: "Rašome",
    h2: "Pastabos apie mažo *objekto* valdymą",
    lede: "Praktiniai tekstai apie rezervacijas, sąskaitas ir kasdienį darbą — nepriklausomiems viešbučiams, nameliams, svečių namams ir apartamentams.",
    readingTime: "min skaitymo",
    back: "Grįžti į blogą",
    metaTitle: "Revoo blogas — rezervacijos, sąskaitos ir mažo objekto valdymas",
    metaDescription:
      "Praktiniai straipsniai viešbučiams, nameliams, svečių namams ir apartamentams: apgyvendinimo valdymo sistemos pasirinkimas, PVM sąskaitos, kambarinių darbas ir tiesioginės rezervacijos.",
    disclaimer:
      "Šis straipsnis yra bendro pobūdžio informacija, o ne mokestinė ar teisinė konsultacija. Konkrečius atvejus derinkite su savo buhalteriu arba VMI.",
    ctaTitle: "Įdomu, ar Revoo tinka jūsų objektui?",
    ctaBody: "Vienas 45 minučių pokalbis ir sąžiningas atsakymas bet kuriuo atveju.",
    ctaButton: "Užsisakyti demo",
  },
  notFound: {
    title: "Puslapis nerastas",
    body: "Tokio adreso nėra arba jis pasikeitė.",
    cta: "Grįžti į pagrindinį puslapį",
  },
  media: {
    missing: "Medžiagos failo nėra",
    browserUrl: "app.revoo.site",
    alt: {
      calendar: "Revoo rezervacijų kalendorius: vienetai eilutėse, dienos stulpeliuose, velkamos rezervacijos",
      housekeepingApp: "Revoo kambarinių programėlė telefone su šios dienos kambariais pagal skubumą",
      housekeepingWeek: "Revoo savaitės tvarkymo lentelė su kiekvieno kambario darbo tipais",
      invoice: "Revoo sugeneruota PVM sąskaita faktūra, paruošta PDF formatu",
      bookingSite: "Su Revoo sukurta rezervacijų svetainė su laisvomis datomis ir kainomis",
    },
  },
  mobileCta: {
    text: "Užsisakyti demo",
    dismiss: "Slėpti juostą",
  },
};

export const copy = { en, lt } as const;
export type Copy = typeof en;
