import type { Copy } from "./copy.types";

export const lt: Copy = {
  nav: {
    product: "Produktas",
    approach: "Mūsų požiūris",
    who: "Kas renkasi Revoo",
    blog: "Naujienos",
    faq: "DUK",
    cta: "Užsisakyti demo",
    langLabel: "Kalba",
    skip: "Pereiti prie turinio",
    home: "Pradžia",
  },
  hero: {
    eyebrow: "PROGRAMINĖ ĮRANGA SU NUOSAVA REZERVACIJŲ SVETAINE JŪSŲ APGYVENDINIMO VERSLUI\n\n",
    h1: "Programinė įranga, *prisitaikanti* prie Jūsų verslo, o ne verčianti verslą prisitaikyti prie jos.",
    sub: "Viešbučiai, nameliai, svečių namai ir apartamentai veikia skirtingai. Vis dėlto dauguma programinės įrangos sprendimų visus verčia dirbti vienodai.\nRevoo - platforma, pritaikyta būtent Jūsų veiklai. Su rezervacijų sveitaine, kuri yra personalizuotai sukurta Jums.",
    primary: "Užsisakyti demo",
    secondary: "Kaip tai veikia",
    status: "Parašykite mums ir suteiksime prieigą išbandyti produktą jau šiandien.",
  },
  carousel: {
    label: "Produkto vaizdai",
    prev: "Ankstesnė skaidrė",
    next: "Kita skaidrė",
    goTo: "Rodyti skaidrę",
    slides: [
      "Perkelkite rezervaciją vos keliais paspaudimais.",
      "Kambarių priežiūros programa, padedanti prioritetizuoti ir sklandžiai perduoti užduotis.",
      "Sąskaitų generavimas Jūsų klientui.",
      "Sukurta pagal Jūsų verslą. Veikia pagal Jūsų taisykles.",
    ],
    alts: {
      booking: "Revoo rezervacijų kalendorius, rodantis rezervacijas pagal vienetus ir datas",
      housekeeping: "Revoo kambarių priežiūros tvarkaraštis su užduotimis, surikiuotomis pagal skubumą",
      invoice: "Svečiui sugeneruota sąskaita Revoo sistemoje",
      notification: "Automatinis el. laiškas, išsiųstas svečiui",
      dashboard: "Revoo administravimo skydelis su rezervacijų ir pajamų apžvalga",
      websiteCalendar: "Rezervacijų svetainė su užimtumo kalendoriumi svečiams",
      website1: "Viešbučio rezervacijų svetainės pradžios puslapis su rezervacijos lauku",
      website2: "Viešbučio rezervacijų svetainės kambarių pasirinkimo ir apmokėjimo puslapis",
    },
  },
  approach: {
    eyebrow: "Mūsų požiūris",
    h2: "Konfigūracija nėra *pritaikymas*",
    lede: "Jūsų sukurtas verslas turi savo charakterį. Mes pasirūpinsime, kad jį matytų ir Jūsų klientai.",
    cardA: {
      title: "Esame šalia nuo pirmos dienos",
      body: "Įsigiliname į jūsų veiklą - nuo papildomų paslaugų ir atsiskaitymų iki kasdienių komandos procesų. Kartu su jumis įdiegiame ir paleidžiame sistemą, o vėliau nuolat ją prižiūrime, kad ji sklandžiai veiktų ir prisitaikytų prie jūsų poreikių.",
    },
    cardB: {
      title: "Tai daugiau nei mėnesinė prenumerata",
      body: "Gaunate ne standartinį sprendimą, prie kurio turi prisitaikyti jūsų verslas, o sistemą, kuri prisitaiko prie jūsų. Negana to ir rezervacijų svetainę, kuri priklauso tik jums.",
    },
  },
  week: {
    eyebrow: "REZERVACIJŲ VALDYMAS",
    h2: "Visas mėnuo *viename* ekrane",
    lede: "Objektai kairėje, dienos viršuje. Perkelkite rezervaciją į kitą dieną ar kitą savaitę - ji tiesiog persikels.",
    points: [
      "Dvigubos rezervacijos identifikuojamos dar prieš jas sukuriant, o ne pastebimos tik tada, kai svečias jau stovi prie durų.",
      "Spustelėkite tuščią langelį ir sukurkite rezervaciją - objektas ir datos bus užpildyti automatiškai.",
      "Užimtumas, importuotas iš Booking.com ir Airbnb, matomas tame pačiame lange ir pažymimas kaip išorinė rezervacija.",
    ],
  },
  morning: {
    eyebrow: "KAMBARIŲ PRIEŽIŪROS VALDYMAS",
    h2: "Jūsų komanda iš karto žino, ką ir kada reikia padaryti.",
    lede: "Revoo automatiškai patikrina šiandienos rezervacijas ir kiekvienai patalpai sudėlioja reikalingus darbus pagal svarbumą.",
    points: [
      "Pirmiausia rodomos patalpos, kurias reikia paruošti tą pačią dieną.",
      "Jei patalpos nebuvo sutvarkytos laiku, užduotis nep,irštama - ji lieka sistemoje, kol bus atlikta.",
      "Jei svečias užsisakė papildomų paslaugų, valdytojas jas mato savo užduočių sąraše, tad tai neliks pamiršta.",
      "Pastebėjus gedimą, apie jį galima pranešti vienu paspaudimu. Vadovas informaciją iš karto mato savo sistemoje.",
      "Valytojas mato tik tai, ko reikia darbuo atlikti. Svečių kontaktai, kainos, mokėjimų informacija ir kita konfidenciali informacija, nėra atvaizduojama.",
    ],
  },
  paperwork: {
    eyebrow: "SĄSKAITOS",
    h2: "Svečias išvyksta. Sąskaita jau *paruošta.*",
    lede: "Sąskaita sugeneruojama automatiškai: su nuosekliu numeriu, jūsų įmonės rekvizitais, PVM arba ne PVM sąskaitos formatu, bei paruošiama PDF formatu. Jokių \"Excel\" lentelių, duomenų perrašinėjimo ar spragų sąskaitų numeracijoje, dėl kurių vėliau kyla rūpesčių.",
    points: [
      "Verslo klientų duomenys surenkami iš anksto: įmonės pavadinimas, įmonės kodas, PVM mokėtojo kodas ir adresas nurodomi užsakymo metu - nereikia jų ieškoti po viešnagės.",
      "Sąskaitų numeriai suteikiami iš eilės, todėl numeracijoje nelieka praleistų numerių.",
      "\u00a0Kiekviena papildomai užsakyta ir apmokėta paslauga įtraukiama kaip atskira eilutė sąskaitoje.",
      "Sąskaitų išrašymas pritaikomos pagal jūsų šalies reikalavimus.",
    ],
  },
  channel: {
    eyebrow: "Jūsų rezervacijų kanalas",
    h2: "Ne rezervacijų langelis, o tikra jūsų rezervacijų svetainė",
    lede: "Dauguma sistemų siūlo rezervacijų modulį, kurį tiesiog įdedate į savo jau turimą svetainę. Jis veikia, bet dažnai atrodo kaip svetimas elementas - skiriasi dizainas, šriftai, tarpai ar net kalba.\nRevoo veikia kitaip. Jūsų svetainė yra rezervacijų sistema. Viskas atrodo taip, kaip ir turi atrodyti - jūsų dizainas, jūsų domenas, jūsų tekstai. O už viso to veikia ta pati sistema, kurią naudojate rezervacijoms ir administravimui.",
    note: "Visa tai veikia per dokumentuotą REST API, todėl Revoo lengva prijungti prie kitų sistemų. API turi atskirus prieigos raktus, leidžiamų domenų sąrašą ir užklausų limitus. Tai reiškia, kad norint prijungti mobiliąją programėlę, partnerio sistemą ar dar vieną rezervacijų kanalą, nereikės kurti visko iš naujo - užteks sukonfigūruoti jau veikiančią sistemą.",
  },
  segments: {
    eyebrow: "Sukurta jūsų objekto tipui",
    h2: "Sukurta pagal tai, kaip dirbate jūs.",
    prev: "Ankstesnis objekto tipas",
    next: "Kitas objekto tipas",
    goTo: "Rodyti objekto tipą",
    slides: [
      {
        title: "Viešbučiams",
        body: "Kambariai, kainos ir registratūra - viskas, ko reikia kasdieniam viešbučio darbui. Revoo suteikia jums patogų rezervacijų kalendorių, valymo darbų sistemą ir sąskaitų išrašymą, be brangių viešbučių valdymų sistemų ir mėnesius trunkančio sudėtingo diegimo.",
      },
      {
        title: "Nameliams",
        body: "Namelio nuoma dažnai priklauso nuo to, kaip greitai ir sklandžiai jis paruošiamas kitam svečiui. Revoo automatiškai parodo, kuriuos namelius šiandien reikia sutvarkyti ir paruošti, durų kodą išsiunčia tik patvirtinus rezervaciją, o visą sezoną galite matyti viename ekrane.",
      },
      {
        title: "Svečių namams",
        body: "Dažnai visus darbus atlieka vienas žmogus - nuo rezervacijų ir svečių aptarnavimo iki valymo organizavimo, bei sąskaitų išrašymo. Revoo viską sujungia vienoje vietoje, todėl net ir vienam žmogui lengviau susitvarkyti su kasdieniais darbais ir ne visada būti vietoje.",
      },
      {
        title: "Apartamentams",
        body: "Jūsų apartamentai nebūtinai turi būti viename pastate ar net vienoje vietoje. Revoo kiekvieną apartamentą valdo kaip atskirą būstą, todėl net skirtingais adresais esančiųs apartamentus galite patogiai valdyti iš vieno bendro kalendoriaus.",
      },
    ],
  },
  ctaBand: {
    text: "Įdomu, ar tai tinka jūsų objektui? Vienas 45 minučių pokalbis atsakys.",
    button: "Užsisakyti demo",
  },
  included: {
    eyebrow: "Ką gaunate",
    h2: "Kas yra platformoje ir ką *sukuriame* jums",
    lede: "Verčiau būsime tikslūs nei įspūdingi. Štai sąžiningas padalijimas.",
    left: {
      title: "Platformoje nuo pirmos dienos",
      sub: "Veikia šiandien, realiai.",
      items: [
        "Kelių objektų skydelis su užimtumo, pajamų ir išlaidų rodikliais",
        "Velkamas rezervacijų kalendorius su dvigubų rezervacijų prevencija",
        "Kainų pakopos pagal naktų skaičių ir apmokamos papildomos paslaugos",
        "Automatiniai laiškai svečiui — patvirtinimas, pakeitimas, atšaukimas, priminimas prieš atvykimą, atsiliepimo prašymas — svečio kalba",
        "Sąskaitų generavimas su nuoseklia numeracija ir PDF",
        "Kambarių tvarkymo modulis su automatiniu darbo tipo nustatymu ir mobilia programėle personalui",
        "Rolės ir kvietimai el. paštu jūsų komandai",
        "Užimtumo importas iš Booking.com ir Airbnb per iCal",
        "Dokumentuotas viešas REST API su raktais, domenų sąrašu ir ribojimais",
        "Teisinių dokumentų valdymas, tiekiamas tiesiai į svečių svetainę",
      ],
    },
    right: {
      title: "Sukuriama jūsų diegimo metu",
      sub: "Apibrėžiama per pirmą pokalbį, statoma pagal jūsų objektą.",
      items: [
        "Jūsų rezervacijų svetainė — sukurta jūsų objektui, jūsų domene",
        "Mokėjimai — prijungiame tą sprendimą, kurį realiai naudojate",
        "Sąskaitos pagal jūsų šalies taisykles — identifikatoriai, tarifai ir numeracija, kurių tikisi mokesčių administratorius",
        "Jūsų kalbos — sąsajoje ir laiškuose svečiams",
        "Tos kanalų jungtys, kurių jūsų objektui realiai reikia",
        "Kad ir ką parduotumėte šalia kambario",
        "Esamų rezervacijų perkėlimas, vienetų, kainų ir taisyklių sukonfigūravimas",
        "Komandos mokymai jų kalba",
      ],
    },
  },
  fit: {
    eyebrow: "Kam skirta",
    h2: "Kam tai tinka — ir kam *netinka*",
    lede: "Pasakius tai garsiai, abu sutaupome skambutį.",
    yesTitle: "Tinka, jei",
    noTitle: "Netinka, jei",
    yes: [
      "6–30 vienetų, valdoma savininko arba mažos komandos",
      "Viešbučiai, nameliai, svečių namai arba apartamentai keliais adresais",
      "Parduodate ne tik kambarį — kad ir kas tai būtų jūsų objekte",
      "Verslo klientai, kuriems reikia tikros sąskaitos įmonei",
      "Tvarkymo komanda, šiuo metu derinama telefonu, popieriuje ar per WhatsApp",
      "Per didelė pajamų dalis atitenka OTA komisiniams",
      "Norite svetainės, kuri atrodo kaip jūsų objektas, o ne kaip programa",
    ],
    no: [
      "Vienas objektas, valdomas kaip papildomos pajamos, o ne kaip verslas",
      "Tinklai ir grupės virš maždaug 50 vienetų",
      "Nuo pirmos dienos reikia pilno dvipusio kanalų valdymo per daug OTA",
      "Norite užsiregistruoti šįvakar internetu ir susikonfigūruoti patys — mes taip nedirbame",
    ],
  },
  start: {
    eyebrow: "Kaip pradėti",
    h2: "Kaip tai iš tikrųjų *prasideda*",
    lede: "Jokios kortelės formos ir jokio 14 dienų bandymo, kurį mestumėte trečią dieną.",
    steps: [
      {
        title: "Pokalbis",
        body: "Apie 45 minutes. Kaip veikia jūsų objektas, ką parduodate šalia kambario, kas šiandien lūžta ir kaip turi atrodyti jūsų sąskaitos. Sąžiningai pasakome, ar tinkame vieni kitiems.",
      },
      {
        title: "Diegimas",
        body: "Sukonfigūruojame vienetus, kainas, papildomas paslaugas ir taisykles, sukuriame rezervacijų svetainę, prijungiame mokėjimų sprendimą ir pritaikome sąskaitas jūsų šaliai. Peržiūrite tai, kol darome.",
      },
      {
        title: "Paleidimas",
        body: "Esamos rezervacijos persikelia. Apmokome registratūrą ir kambarines jų kalba. Tada liekame šalia visą pirmą sezoną.",
      },
    ],
    cta: "Užsisakyti demo",
  },
  demo: {
    eyebrow: "Susisiekime",
    h2: "Pažiūrėkime į jūsų *objektą*",
    lede: "Papasakokite apie jį truputį, ir per vieną darbo dieną grįšime arba su demo laiku, arba su sąžiningu \u201Emes jums netinkame\u201C.",
    facts: [
      "hello@revoo.site",
      "Dirbame anglų ir lietuvių kalbomis",
      "Įsikūrę Lietuvoje · pradedame dirbti su objektais Islandijoje",
    ],
    form: {
      name: "Vardas",
      email: "El. paštas",
      property: "Objekto pavadinimas",
      country: "Šalis",
      countries: ["Islandija", "Lietuva", "Latvija", "Estija", "Norvegija", "Vokietija", "Kita"],
      type: "Objekto tipas",
      types: ["Viešbutis", "Nameliai", "Svečių namai", "Apartamentai", "Kita"],
      units: "Vienetų skaičius",
      unitOptions: ["1–5", "6–15", "16–30", "31–50", "50+"],
      current: "Ką naudojate šiandien",
      currentOptions: [
        "Lentelė ar popierius",
        "Tik Booking.com extranet",
        "Kita PMS",
        "Rezervacijų langelis svetainėje",
        "Kita",
      ],
      notes: "Ką dar turėtume žinoti?",
      optional: "neprivaloma",
      required: "privaloma",
      submit: "Užsisakyti demo",
      fineprint: "Atsakome per vieną darbo dieną. Jokių automatinių sekų.",
      select: "Pasirinkite",
    },
    success: {
      title: "Ačiū",
      body: "Susisieksime per vieną darbo dieną.",
    },
  },
  faq: {
    eyebrow: "Klausimai",
    h2: "Ką žmonės iš tikrųjų *klausia*",
    items: [
      {
        q: "Kiek tai kainuoja?",
        a: "Yra vienkartinis diegimo mokestis ir mėnesinė prenumerata. Diegimo mokestis priklauso nuo apimties — kiek vienetų, ką parduodate šalia kambario, ar reikia naujos svetainės, koks mokėjimų sprendimas, kurios šalies sąskaitos. Kainą pasakome po pirmo pokalbio, o ne prieš jį, nes akla kaina būtų neteisinga viena ar kita kryptimi.",
      },
      {
        q: "Ar tvarkote mokėjimus?",
        a: "Diegimo metu prijungiame tą mokėjimų sprendimą, kurį realiai naudojate. Tai nėra varnelė nustatymuose — tai apibrėžiama ir sukuriama jūsų atvejui, todėl veikia su ta įstaiga, su kuria jau turite sutartį.",
      },
      {
        q: "Ar sinchronizuojasi su Booking.com ir Airbnb?",
        a: "Užimtumo importas per iCal veikia šiandien, todėl išorinės rezervacijos matomos kalendoriuje ir užima vienetą. Gilesnės kanalų jungtys apibrėžiamos kaip diegimo dalis, kai objektui to reikia. Sąmoningai neteigiame, kad esame 200 kanalų channel manager — jei to reikia nuo pirmos dienos, didelė platforma jums tiks geriau, ir mes tai pasakysime.",
      },
      {
        q: "Ar galiu pasilikti dabartinę svetainę?",
        a: "Taip — ji gali jungtis prie Revoo per viešą API. Bet jei dabartinė svetainė negali priimti rezervacijos nenusiųsdama svečio kitur, jos pakeitimas paprastai yra tas vienas pokytis, kuris atsiperka už visą projektą.",
      },
      {
        q: "Kodėl nėra registracijos mygtuko?",
        a: "Nes kiekvienam objektui, kurį diegėme, reikėjo kažko, ko nereikėjo ankstesniam. Savitarnos registracija paduotų jums tuščią skydelį ir nustatymų puslapį, o diegimą darytumėte patys. Mes verčiau padarysime tai kaip reikia.",
      },
      {
        q: "Kas bus, jei jus peraugsiu?",
        a: "Platforma sukurta pagal API-first principą, o duomenys yra jūsų — objektai, rezervacijos, svečiai ir sąskaitos, viskas eksportuojama. Verčiau išeisite tvarkingai, nei jausitės įstrigę.",
      },
      {
        q: "Kur esate įsikūrę?",
        a: "Lietuvoje. Platforma šiandien veikia realiai, ir pradedame dirbti su objektais Islandijoje. Dirbame anglų ir lietuvių kalbomis.",
      },
    ],
  },
  footer: {
    tagline:
      "Apgyvendinimo valdymo sistema ir rezervacijų svetainė nepriklausomiems viešbučiams, nameliams, svečių namams ir apartamentams.",
    linksTitle: "Svetainė",
    langTitle: "Kalba",
    rights: "© 2026 Revoo",
    contact: "revoo.site · hello@revoo.site",
  },
  blog: {
    title: "Blogas",
    eyebrow: "Rašome",
    h2: "Pastabos apie mažo *objekto* valdymą",
    lede: "Praktiniai tekstai apie rezervacijas, sąskaitas ir kasdienį darbą — nepriklausomiems viešbučiams, nameliams, svečių namams ir apartamentams.",
    readingTime: "min skaitymo",
    back: "Grįžti į blogą",
    metaTitle: "Revoo blogas — rezervacijos, sąskaitos ir mažo objekto valdymas",
    metaDescription:
      "Praktiniai straipsniai viešbučiams, nameliams, svečių namams ir apartamentams: apgyvendinimo valdymo sistemos pasirinkimas, PVM sąskaitos, kambarinių darbas ir tiesioginės rezervacijos.",
    disclaimer:
      "Šis straipsnis yra bendro pobūdžio informacija, o ne mokestinė ar teisinė konsultacija. Konkrečius atvejus derinkite su savo buhalteriu arba VMI.",
    ctaTitle: "Įdomu, ar Revoo tinka jūsų objektui?",
    ctaBody: "Vienas 45 minučių pokalbis ir sąžiningas atsakymas bet kuriuo atveju.",
    ctaButton: "Užsisakyti demo",
  },
  notFound: {
    title: "Puslapis nerastas",
    body: "Tokio adreso nėra arba jis pasikeitė.",
    cta: "Grįžti į pagrindinį puslapį",
  },
  media: {
    missing: "Medžiagos failo nėra",
    browserUrl: "app.revoo.site",
    alt: {
      calendar: "Revoo rezervacijų kalendorius: vienetai eilutėse, dienos stulpeliuose, velkamos rezervacijos",
      housekeepingApp: "Revoo kambarinių programėlė telefone su šios dienos kambariais pagal skubumą",
      housekeepingWeek: "Revoo savaitės tvarkymo lentelė su kiekvieno kambario darbo tipais",
      invoice: "Revoo sugeneruota PVM sąskaita faktūra, paruošta PDF formatu",
      bookingSite: "Su Revoo sukurta rezervacijų svetainė su laisvomis datomis ir kainomis",
    },
  },
  mobileCta: {
    text: "Užsisakyti demo",
    dismiss: "Slėpti juostą",
  },
};
