import type { Copy } from "./copy.types";

export const lt: Copy = {
  nav: {
    product: "Produktas",
    approach: "Mūsų požiūris",
    who: "Kas renkasi Revoo",
    blog: "Naujienos",
    faq: "DUK",
    cta: "Užsisakyti demo",
    langLabel: "Kalba",
    skip: "Pereiti prie turinio",
    home: "Pradžia",
  },
  hero: {
    eyebrow: "PROGRAMINĖ ĮRANGA SU NUOSAVA REZERVACIJŲ SVETAINE JŪSŲ APGYVENDINIMO VERSLUI\n\n",
    h1: "Programinė įranga, *prisitaikanti* prie Jūsų verslo, o ne verčianti verslą prisitaikyti prie jos.",
    sub: "Viešbučiai, nameliai, svečių namai ir apartamentai veikia skirtingai. Vis dėlto dauguma programinės įrangos sprendimų visus verčia dirbti vienodai.\nRevoo - platforma, pritaikyta būtent Jūsų veiklai. Su rezervacijų sveitaine, kuri yra personalizuotai sukurta Jums.",
    primary: "Užsisakyti demo",
    secondary: "Kaip tai veikia",
    status: "Parašykite mums ir suteiksime prieigą išbandyti produktą jau šiandien.",
  },
  carousel: {
    label: "Produkto vaizdai",
    prev: "Ankstesnė skaidrė",
    next: "Kita skaidrė",
    goTo: "Rodyti skaidrę",
    slides: [
      "Perkelkite rezervaciją vos keliais paspaudimais.",
      "Kambarių priežiūros programa, padedanti prioritetizuoti ir sklandžiai perduoti užduotis.",
      "Sąskaitų generavimas Jūsų klientui.",
      "Sukurta pagal Jūsų verslą. Veikia pagal Jūsų taisykles.",
    ],
    alts: {
      booking: "Revoo rezervacijų kalendorius, rodantis rezervacijas pagal vienetus ir datas",
      housekeeping: "Revoo kambarių priežiūros tvarkaraštis su užduotimis, surikiuotomis pagal skubumą",
      invoice: "Svečiui sugeneruota sąskaita Revoo sistemoje",
      notification: "Automatinis el. laiškas, išsiųstas svečiui",
      dashboard: "Revoo administravimo skydelis su rezervacijų ir pajamų apžvalga",
      websiteCalendar: "Rezervacijų svetainė su užimtumo kalendoriumi svečiams",
      website1: "Viešbučio rezervacijų svetainės pradžios puslapis su rezervacijos lauku",
      website2: "Viešbučio rezervacijų svetainės kambarių pasirinkimo ir apmokėjimo puslapis",
    },
  },
  approach: {
    eyebrow: "Mūsų požiūris",
    h2: "Konfigūracija nėra *pritaikymas*",
    lede: "Jūsų sukurtas verslas turi savo charakterį. Mes pasirūpinsime, kad jį matytų ir Jūsų klientai.",
    cardA: {
      title: "Esame šalia nuo pirmos dienos",
      body: "Įsigiliname į jūsų veiklą - nuo papildomų paslaugų ir atsiskaitymų iki kasdienių komandos procesų. Kartu su jumis įdiegiame ir paleidžiame sistemą, o vėliau nuolat ją prižiūrime, kad ji sklandžiai veiktų ir prisitaikytų prie jūsų poreikių.",
    },
    cardB: {
      title: "Tai daugiau nei mėnesinė prenumerata",
      body: "Gaunate ne standartinį sprendimą, prie kurio turi prisitaikyti jūsų verslas, o sistemą, kuri prisitaiko prie jūsų. Negana to ir rezervacijų svetainę, kuri priklauso tik jums.",
    },
  },
  week: {
    eyebrow: "REZERVACIJŲ VALDYMAS",
    h2: "Visas mėnuo *viename* ekrane",
    lede: "Objektai kairėje, dienos viršuje. Perkelkite rezervaciją į kitą dieną ar kitą savaitę - ji tiesiog persikels.",
    points: [
      "Dvigubos rezervacijos identifikuojamos dar prieš jas sukuriant, o ne pastebimos tik tada, kai svečias jau stovi prie durų.",
      "Spustelėkite tuščią langelį ir sukurkite rezervaciją - objektas ir datos bus užpildyti automatiškai.",
      "Užimtumas, importuotas iš Booking.com ir Airbnb, matomas tame pačiame lange ir pažymimas kaip išorinė rezervacija.",
    ],
  },
  morning: {
    eyebrow: "KAMBARIŲ PRIEŽIŪROS VALDYMAS",
    h2: "Jūsų komanda iš karto žino, ką ir kada reikia padaryti.",
    lede: "Revoo automatiškai patikrina šiandienos rezervacijas ir kiekvienai patalpai sudėlioja reikalingus darbus pagal svarbumą.",
    points: [
      "Pirmiausia rodomos patalpos, kurias reikia paruošti tą pačią dieną.",
      "Jei patalpos nebuvo sutvarkytos laiku, užduotis nep,irštama - ji lieka sistemoje, kol bus atlikta.",
      "Jei svečias užsisakė papildomų paslaugų, valdytojas jas mato savo užduočių sąraše, tad tai neliks pamiršta.",
      "Pastebėjus gedimą, apie jį galima pranešti vienu paspaudimu. Vadovas informaciją iš karto mato savo sistemoje.",
      "Valytojas mato tik tai, ko reikia darbuo atlikti. Svečių kontaktai, kainos, mokėjimų informacija ir kita konfidenciali informacija, nėra atvaizduojama.",
    ],
  },
  paperwork: {
    eyebrow: "SĄSKAITOS",
    h2: "Svečias išvyksta. Sąskaita jau *paruošta.*",
    lede: "Sąskaita sugeneruojama automatiškai: su nuosekliu numeriu, jūsų įmonės rekvizitais, PVM arba ne PVM sąskaitos formatu, bei paruošiama PDF formatu. Jokių \"Excel\" lentelių, duomenų perrašinėjimo ar spragų sąskaitų numeracijoje, dėl kurių vėliau kyla rūpesčių.",
    points: [
      "Verslo klientų duomenys surenkami iš anksto: įmonės pavadinimas, įmonės kodas, PVM mokėtojo kodas ir adresas nurodomi užsakymo metu - nereikia jų ieškoti po viešnagės.",
      "Sąskaitų numeriai suteikiami iš eilės, todėl numeracijoje nelieka praleistų numerių.",
      "\u00a0Kiekviena papildomai užsakyta ir apmokėta paslauga įtraukiama kaip atskira eilutė sąskaitoje.",
      "Sąskaitų išrašymas pritaikomos pagal jūsų šalies reikalavimus.",
    ],
  },
  channel: {
    eyebrow: "Jūsų rezervacijų kanalas",
    h2: "Ne rezervacijų langelis, o tikra jūsų rezervacijų svetainė",
    lede: "Dauguma sistemų siūlo rezervacijų modulį, kurį tiesiog įdedate į savo jau turimą svetainę. Jis veikia, bet dažnai atrodo kaip svetimas elementas - skiriasi dizainas, šriftai, tarpai ar net kalba.\nRevoo veikia kitaip. Jūsų svetainė yra rezervacijų sistema. Viskas atrodo taip, kaip ir turi atrodyti - jūsų dizainas, jūsų domenas, jūsų tekstai. O už viso to veikia ta pati sistema, kurią naudojate rezervacijoms ir administravimui.",
    note: "Visa tai veikia per dokumentuotą REST API, todėl Revoo lengva prijungti prie kitų sistemų. API turi atskirus prieigos raktus, leidžiamų domenų sąrašą ir užklausų limitus. Tai reiškia, kad norint prijungti mobiliąją programėlę, partnerio sistemą ar dar vieną rezervacijų kanalą, nereikės kurti visko iš naujo - užteks sukonfigūruoti jau veikiančią sistemą.",
  },
  segments: {
    eyebrow: "Sukurta jūsų objekto tipui",
    h2: "Sukurta pagal tai, kaip dirbate jūs.",
    prev: "Ankstesnis objekto tipas",
    next: "Kitas objekto tipas",
    goTo: "Rodyti objekto tipą",
    slides: [
      {
        title: "Viešbučiams",
        body: "Kambariai, kainos ir registratūra - viskas, ko reikia kasdieniam viešbučio darbui. Revoo suteikia jums patogų rezervacijų kalendorių, valymo darbų sistemą ir sąskaitų išrašymą, be brangių viešbučių valdymų sistemų ir mėnesius trunkančio sudėtingo diegimo.",
      },
      {
        title: "Nameliams",
        body: "Namelio nuoma dažnai priklauso nuo to, kaip greitai ir sklandžiai jis paruošiamas kitam svečiui. Revoo automatiškai parodo, kuriuos namelius šiandien reikia sutvarkyti ir paruošti, durų kodą išsiunčia tik patvirtinus rezervaciją, o visą sezoną galite matyti viename ekrane.",
      },
      {
        title: "Svečių namams",
        body: "Dažnai visus darbus atlieka vienas žmogus - nuo rezervacijų ir svečių aptarnavimo iki valymo organizavimo, bei sąskaitų išrašymo. Revoo viską sujungia vienoje vietoje, todėl net ir vienam žmogui lengviau susitvarkyti su kasdieniais darbais ir ne visada būti vietoje.",
      },
      {
        title: "Apartamentams",
        body: "Jūsų apartamentai nebūtinai turi būti viename pastate ar net vienoje vietoje. Revoo kiekvieną apartamentą valdo kaip atskirą būstą, todėl net skirtingais adresais esančiųs apartamentus galite patogiai valdyti iš vieno bendro kalendoriaus.",
      },
    ],
  },
  ctaBand: {
    text: "Įdomu, ar Revoo tiktų jūsų apgyvendimo vietai?\u00a0\n45 minučių pokalbio pakaks, kad tai išsiaiškintume.",
    button: "Užsisakyti demo",
  },
  included: {
    eyebrow: "Ką gaunate",
    h2: "Kas jau yra platformoje ir tai ką *sukuriame* jums",
    lede: "Mums svarbiau aiškumas nei įspūdis. Todėl atvirai parodome, kas jau yra Revoo platformoje, o ką papildomai pritaikome būtent jums.",
    left: {
      title: "Jau paruošta naudoti.",
      sub: "Visos šios funkcijos jau yra paruoštos naudoti.",
      items: [
        "Kelių būstų valdymas vienoje vietoje – matote užimtumą, pajamas ir išlaidas.",
        "Patogus rezervacijų kalendorius – rezervacijas galite perkelti tiesiog paspaudimu, o sistema neleidžia sukurti dvigubos rezervacijos.",
        "Lanksčios kainos pagal viešnagės trukmę ir papildomai užsakomos paslaugos kiekvienam būstui.",
        "Automatiniai laiškai svečiams – rezervacijos patvirtinimas, pakeitimai, atšaukimas, priminimas prieš atvykimą ir prašymas palikti atsiliepimą. Laiškai siunčiami svečio kalba.",
        "Automatinis sąskaitų išrašymas – nuosekli numeracija ir PDF formatas.",
        "Valymo darbų valdymas – sistema pati nustato, kokio tipo darbą reikia atlikti, o valytojai užduotis mato mobiliojoje programėlėje.",
        "Komandos valdymas – galite priskirti skirtingas roles ir pakviesti komandos narius el. paštu.",
        "Rezervacijų prieinamumo sinchronizavimas su „Booking.com“ ir „Airbnb“ per iCal.",
        "Vieša REST API – su prieigos raktais, leidžiamų domenų sąrašu ir užklausų limitais, kad „Revoo“ būtų lengva prijungti prie kitų sistemų.",
        "Teisiniai dokumentai – reikalingi dokumentai gali būti pateikiami tiesiai jūsų svečiams jūsų rezervacijų svetainėje.",
      ],
    },
    right: {
      title: "Pritaikome pagal jūsų poreikius.",
      sub: "Viską aptariame iš anksto ir pritaikome konkrečiai jūsų apgyvendinimo vietai.",
      items: [
        "Jūsų rezervacijų svetainė – sukurta pagal jūsų poreikius ir veikianti jūsų domene.",
        "Mokėjimai – prijungiame tą mokėjimų tiekėją, kurį iš tikrųjų naudojate.",
        "Sąskaitų išrašymas pagal jūsų šalies reikalavimus – naudojami reikalingi rekvizitai, PVM tarifai ir sąskaitų numeracija.",
        "Jūsų tekstai – tiek sistemos aplinkoje, tiek laiškuose svečiams.",
        "Reikalingi rezervacijų kanalai – prijungiame būtent tuos kanalus, kuriuos naudojate savo veikloje.",
        "Papildomos paslaugos – įdiegiame galimybę parduoti ir valdyti tai, ką siūlote kartu su apgyvendinimu.",
        "Esamų rezervacijų perkėlimas – perkeliame turimas rezervacijas ir paruošiame būstus, kainas bei taisykles.",
        "Komandos apmokymai – apmokome jūsų komandą jų kalba.",
      ],
    },
  },
  fit: {
    eyebrow: "KAS RENKASI REVOO",
    h2: "Kam Revoo tinka — ir kam *ne.*",
    lede: "Geriau tai pasakyti iš karto - taip sutaupysime laiko ir jums, ir mums.",
    yesTitle: "Šis produktas jums, jei:",
    noTitle: "Produktas gali jums netikti, jei:",
    yes: [
      "Turite 6–30 būstų ir juos valdote patys arba su nedidele komanda.",
      "Valdote viešbutį, namelius, svečių namus ar apartamentus, net jei jie yra skirtingais adresais.",
      "Siūlote svečiams ne tik apgyvendinimą, bet ir papildomas paslaugas.",
      "Priimate verslo klientus, kuriems reikalingos sąskaitos įmonei.",
      "Valymo darbus šiuo metu derinate telefonu, popieriuje ar per „WhatsApp“.",
      "Norite mažiau priklausyti nuo OTA platformų ir jų komisinių.",
      "Norite savo apgyvendinimo vietai pritaikytos svetainės, o ne svetainės, kuri atrodo kaip standartinė programinė įranga.",
    ],
    no: [
      "Turite vieną būstą, kurį nuomojate kaip papildomą pajamų šaltinį, o ne kaip pagrindinę veiklą.",
      "Valdote didelį viešbučių tinklą.",
      "Nuo pat pirmos dienos jums reikia pilno dvipusio sinchronizavimo su daugeliu rezervacijų platformų (OTA).",
      "Norite užsiregistruoti internetu ir viską susikonfigūruoti patys tą pačią dieną – „Revoo“ veikia kitaip: sistemą pritaikome jūsų veiklai ir padedame ją paruošti.",
    ],
  },
  start: {
    eyebrow: "PRADŽIA",
    h2: "Nuo ko pradedame",
    lede: "Jokių kredito kortelės duomenų įvedimo ir jokių 14 dienų bandomųjų versijų, kurias po kelių dienų pamirštumėte.",
    steps: [
      {
        title: "Pokalbis",
        body: "Apie 45 minutes skiriame tam, kad geriau suprastume jūsų veiklą: kaip valdote apgyvendimo vietą, ką siūlote svečiams be apgyvendimo, su kokiomis problemomis susiduriate šiandien ir kaip turi atrodyti jūsų sąskaitos.",
      },
      {
        title: "Sistemos diegimas",
        body: "Sukonfigūruojame jūsų būstus ar patalpas, kainas, papildomas paslaugas ir taisykles, sukuriame rezervacijų svetainę, prijungiame jūsų naudojamą mokėjimų tiekėją ir pritaikome sąskaitų išrašymą pagal jūsų šalies reikalavimus.",
      },
      {
        title: "Paleidimas",
        body: "Perkeliame jūsų esamas rezervacijas į Revoo ir apmokome registratūros bei valymo komandas jomis naudotis.",
      },
    ],
    cta: "Užsisakyti demo",
  },
  demo: {
    eyebrow: "Susisiekime",
    h2: "Papasakokite apie savo apgyvendimo vietą",
    lede: "Trumpai papasakokite apie savo veiklą, o mes su jumis susisieksime per vieną darbo dieną. Pasiūlysime demonstracijos laiką arba atvirtai pasakysime, jei Revoo nėra tinkamiausias sprendimas jūsų verslui.",
    facts: [
      "hello@revoo.site",
      "Bendraujame anglų ir lietuvių kalbomis",
      "Esame Lietuvoje · šiuo metu diegiame Revoo produktos Islandijoje",
    ],
    form: {
      name: "Vardas",
      email: "El. paštas",
      property: "Objekto pavadinimas",
      country: "Šalis",
      countries: ["Islandija", "Lietuva", "Latvija", "Estija", "Norvegija", "Vokietija", "Kita"],
      type: "Objekto tipas",
      types: ["Viešbutis", "Nameliai", "Svečių namai", "Apartamentai", "Kita"],
      units: "Vienetų skaičius",
      unitOptions: ["1–5", "6–15", "16–30", "31–50", "50+"],
      current: "Ką naudojate šiandien",
      currentOptions: [
        "Lentelė ar popierius",
        "Tik Booking.com extranet",
        "Kita PMS",
        "Rezervacijų langelis svetainėje",
        "Kita",
      ],
      notes: "Ką dar turėtume žinoti?",
      optional: "neprivaloma",
      required: "privaloma",
      submit: "Užsisakyti demo",
      fineprint: "Atsakome per vieną darbo dieną. Jokių automatinių laiškų - atsakome asmeniškai.",
      select: "Pasirinkite",
    },
    success: {
      title: "Ačiū",
      body: "Susisieksime per vieną darbo dieną.",
    },
  },
  faq: {
    eyebrow: "DAŽNIAUSIAI UŽDUODAMI KLAUSIMAI",
    h2: "Tai, ko iš tikrųjų klausia žmonės",
    items: [
      {
        q: "Kiek tai kainuoja?",
        a: "Yra vienkartinis sistemos įdiegimo mokestis ir mėnesinis abonementas.\n\nĮdiegimo kaina priklauso nuo to, ko jums reikia: kiek turite būstų, kokias papildomas paslaugas parduodate, ar reikia naujos svetainės, kokį mokėjimų tiekėją naudojate ir pagal kurios šalies reikalavimus turi būti išrašomos sąskaitos.\n\nTikslią kainą pateikiame po pirmo pokalbio, o ne iš anksto. Nenorime pateikti kainos nežinodami Jūsų poreikių.",
      },
      {
        q: "Ar „Revoo“ tvarko mokėjimus?",
        a: "Taip. Diegimo metu prijungiame jūsų naudojamą mokėjimų tiekėją.\n\nTai nėra tiesiog funkcija, kurią įjungiate nustatymuose. Mokėjimus sukonfigūruojame pagal jūsų veiklą ir naudojamą sistemą, todėl galite toliau naudoti jau turimą sutartį su savo mokėjimų paslaugų teikėju.",
      },
      {
        q: "Ar „Revoo“ sinchronizuojasi su „Booking.com“ ir „Airbnb“?",
        a: "Taip. Šiuo metu per iCal galime importuoti rezervacijų prieinamumą, todėl išoriniuose kanaluose gautos rezervacijos atsiranda jūsų „Revoo“ kalendoriuje ir automatiškai užblokuoja būstą.\n\nJei reikia išsamesnės integracijos su rezervacijų kanalais, ją galime pritaikyti diegimo metu pagal jūsų poreikius.\n\nNenorime apsimesti sistema, kuri vienu metu valdo šimtus rezervacijų kanalų. Jei būtent to jums reikia nuo pirmos dienos, didesnė specializuota platforma greičiausiai bus geresnis pasirinkimas – ir mes tai pasakysime atvirai.",
      },
      {
        q: "Ar galiu pasilikti savo dabartinę svetainę?",
        a: "Taip. Ją galima prijungti prie sistemos per viešąją API.\n\nTačiau jei dabartinėje svetainėje svečias negali atlikti rezervacijos ir yra nukreipiamas kitur, nauja rezervacijų svetainė dažnai būna vienas naudingiausių pakeitimų, kuriuos verta atlikti.",
      },
      {
        q: "Kodėl nėra registracijos mygtuko?",
        a: "Nes kiekviena apgyvendinimo vieta turi skirtingų poreikių. Tai, ko reikia vienam verslui, nebūtinai tiks kitam.\n\nRegistracija pačiam reikštų, kad gautumėte tuščią sistemą su nustatymų puslapiu ir viską turėtumėte susikonfigūruoti patys.\n\nMes pasirenkame kitą kelią – pirmiausia išsiaiškiname jūsų poreikius, o tada tinkamai paruošiame sistemą jūsų veiklai.",
      },
      {
        q: "Kas nutiks, jei nuspręsiu pereiti prie kito sprendimo?",
        a: "Sistema sukurta taip, kad ją būtų galima lengvai integruoti su kitomis sistemomis, o jūsų duomenys visada priklauso jums – būstai, rezervacijos, svečių duomenys ir sąskaitos gali būti eksportuojami.\n\nNenorime jūsų „pririšti“ prie sistemos. Jei ateis laikas pereiti prie kito sprendimo, galėsite tai padaryti paprastai ir pasiimti savo duomenis kartu.",
      },
      {
        q: "Kur jūs įsikūrę?",
        a: "Lietuvoje. Platforma jau veikia realiose apgyvendinimo vietose, o šiuo metu pradedame diegti sistemą Islandijoje.\n\nBendraujame lietuvių ir anglų kalbomis.",
      },
    ],
  },
  footer: {
    tagline:
      "Apgyvendinimo vietų valdymo sistema ir rezervacijų svetainė nepriklausomiems viešbučiams, nameliams, svečių namams ir aparatamentams.",
    linksTitle: "Svetainė",
    langTitle: "Kalba",
    rights: "© 2026 Revoo",
    contact: "revoo.site · hello@revoo.site",
  },
  blog: {
    title: "Blogas",
    eyebrow: "Rašome",
    h2: "Pastabos apie mažo *objekto* valdymą",
    lede: "Praktiniai tekstai apie rezervacijas, sąskaitas ir kasdienį darbą — nepriklausomiems viešbučiams, nameliams, svečių namams ir apartamentams.",
    readingTime: "min skaitymo",
    back: "Grįžti į blogą",
    metaTitle: "Revoo blogas — rezervacijos, sąskaitos ir mažo objekto valdymas",
    metaDescription:
      "Praktiniai straipsniai viešbučiams, nameliams, svečių namams ir apartamentams: apgyvendinimo valdymo sistemos pasirinkimas, PVM sąskaitos, kambarinių darbas ir tiesioginės rezervacijos.",
    disclaimer:
      "Šis straipsnis yra bendro pobūdžio informacija, o ne mokestinė ar teisinė konsultacija. Konkrečius atvejus derinkite su savo buhalteriu arba VMI.",
    ctaTitle: "Įdomu, ar Revoo tinka jūsų objektui?",
    ctaBody: "Vienas 45 minučių pokalbis ir sąžiningas atsakymas bet kuriuo atveju.",
    ctaButton: "Užsisakyti demo",
  },
  notFound: {
    title: "Puslapis nerastas",
    body: "Tokio adreso nėra arba jis pasikeitė.",
    cta: "Grįžti į pagrindinį puslapį",
  },
  media: {
    missing: "Medžiagos failo nėra",
    browserUrl: "app.revoo.site",
    alt: {
      calendar: "Revoo rezervacijų kalendorius: vienetai eilutėse, dienos stulpeliuose, velkamos rezervacijos",
      housekeepingApp: "Revoo kambarinių programėlė telefone su šios dienos kambariais pagal skubumą",
      housekeepingWeek: "Revoo savaitės tvarkymo lentelė su kiekvieno kambario darbo tipais",
      invoice: "Revoo sugeneruota PVM sąskaita faktūra, paruošta PDF formatu",
      bookingSite: "Su Revoo sukurta rezervacijų svetainė su laisvomis datomis ir kainomis",
    },
  },
  mobileCta: {
    text: "Užsisakyti demo",
    dismiss: "Slėpti juostą",
  },
};
