/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PrisijungimasRouteImport } from './routes/prisijungimas'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SlaptazodisRouteImport } from './routes/slaptazodis'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiTrackViewRouteImport } from './routes/api/track-view'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as LtIndexRouteImport } from './routes/lt/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAnalitikaRouteImport } from './routes/_authenticated/admin.analitika'
import { Route as AuthenticatedAdminSablonaiRouteImport } from './routes/_authenticated/admin.sablonai'
import { Route as AuthenticatedAdminUzklausosRouteImport } from './routes/_authenticated/admin.uzklausos'
import { Route as AuthenticatedAdminVartotojaiRouteImport } from './routes/_authenticated/admin.vartotojai'
import { Route as LtBlogIndexRouteImport } from './routes/lt/blog/index'
import { Route as LtBlogSlugRouteImport } from './routes/lt/blog/$slug'
import { Route as AuthenticatedAdminPerziuraIdRouteImport } from './routes/_authenticated/admin.perziura.$id'
import { Route as AuthenticatedAdminProjektaiIndexRouteImport } from './routes/_authenticated/admin.projektai.index'
import { Route as AuthenticatedAdminProjektaiIdRouteImport } from './routes/_authenticated/admin.projektai.$id'
import { Route as AuthenticatedAdminProjektaiNustatymaiRouteImport } from './routes/_authenticated/admin.projektai.nustatymai'
import { Route as AuthenticatedAdminRegistrasIndexRouteImport } from './routes/_authenticated/admin.registras.index'
import { Route as AuthenticatedAdminRegistrasIdRouteImport } from './routes/_authenticated/admin.registras.$id'
import { Route as AuthenticatedAdminRegistrasImportasRouteImport } from './routes/_authenticated/admin.registras.importas'
import { Route as AuthenticatedAdminStraipsniaiIndexRouteImport } from './routes/_authenticated/admin.straipsniai.index'
import { Route as AuthenticatedAdminStraipsniaiIdRouteImport } from './routes/_authenticated/admin.straipsniai.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PrisijungimasRoute = PrisijungimasRouteImport.update({
  id: '/prisijungimas',
  path: '/prisijungimas',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SlaptazodisRoute = SlaptazodisRouteImport.update({
  id: '/slaptazodis',
  path: '/slaptazodis',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiTrackViewRoute = ApiTrackViewRouteImport.update({
  id: '/api/track-view',
  path: '/api/track-view',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LtIndexRoute = LtIndexRouteImport.update({
  id: '/lt/',
  path: '/lt/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalitikaRoute =
  AuthenticatedAdminAnalitikaRouteImport.update({
    id: '/analitika',
    path: '/analitika',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSablonaiRoute =
  AuthenticatedAdminSablonaiRouteImport.update({
    id: '/sablonai',
    path: '/sablonai',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUzklausosRoute =
  AuthenticatedAdminUzklausosRouteImport.update({
    id: '/uzklausos',
    path: '/uzklausos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVartotojaiRoute =
  AuthenticatedAdminVartotojaiRouteImport.update({
    id: '/vartotojai',
    path: '/vartotojai',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LtBlogIndexRoute = LtBlogIndexRouteImport.update({
  id: '/lt/blog/',
  path: '/lt/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LtBlogSlugRoute = LtBlogSlugRouteImport.update({
  id: '/lt/blog/$slug',
  path: '/lt/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminPerziuraIdRoute =
  AuthenticatedAdminPerziuraIdRouteImport.update({
    id: '/perziura/$id',
    path: '/perziura/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjektaiIndexRoute =
  AuthenticatedAdminProjektaiIndexRouteImport.update({
    id: '/projektai/',
    path: '/projektai/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjektaiIdRoute =
  AuthenticatedAdminProjektaiIdRouteImport.update({
    id: '/projektai/$id',
    path: '/projektai/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjektaiNustatymaiRoute =
  AuthenticatedAdminProjektaiNustatymaiRouteImport.update({
    id: '/projektai/nustatymai',
    path: '/projektai/nustatymai',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRegistrasIndexRoute =
  AuthenticatedAdminRegistrasIndexRouteImport.update({
    id: '/registras/',
    path: '/registras/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRegistrasIdRoute =
  AuthenticatedAdminRegistrasIdRouteImport.update({
    id: '/registras/$id',
    path: '/registras/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRegistrasImportasRoute =
  AuthenticatedAdminRegistrasImportasRouteImport.update({
    id: '/registras/importas',
    path: '/registras/importas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStraipsniaiIndexRoute =
  AuthenticatedAdminStraipsniaiIndexRouteImport.update({
    id: '/straipsniai/',
    path: '/straipsniai/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStraipsniaiIdRoute =
  AuthenticatedAdminStraipsniaiIdRouteImport.update({
    id: '/straipsniai/$id',
    path: '/straipsniai/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prisijungimas': typeof PrisijungimasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slaptazodis': typeof SlaptazodisRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/track-view': typeof ApiTrackViewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/lt/': typeof LtIndexRoute
  '/admin/analitika': typeof AuthenticatedAdminAnalitikaRoute
  '/admin/sablonai': typeof AuthenticatedAdminSablonaiRoute
  '/admin/uzklausos': typeof AuthenticatedAdminUzklausosRoute
  '/admin/vartotojai': typeof AuthenticatedAdminVartotojaiRoute
  '/lt/blog/$slug': typeof LtBlogSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/lt/blog/': typeof LtBlogIndexRoute
  '/admin/perziura/$id': typeof AuthenticatedAdminPerziuraIdRoute
  '/admin/projektai/$id': typeof AuthenticatedAdminProjektaiIdRoute
  '/admin/projektai/nustatymai': typeof AuthenticatedAdminProjektaiNustatymaiRoute
  '/admin/registras/$id': typeof AuthenticatedAdminRegistrasIdRoute
  '/admin/registras/importas': typeof AuthenticatedAdminRegistrasImportasRoute
  '/admin/straipsniai/$id': typeof AuthenticatedAdminStraipsniaiIdRoute
  '/admin/projektai/': typeof AuthenticatedAdminProjektaiIndexRoute
  '/admin/registras/': typeof AuthenticatedAdminRegistrasIndexRoute
  '/admin/straipsniai/': typeof AuthenticatedAdminStraipsniaiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prisijungimas': typeof PrisijungimasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slaptazodis': typeof SlaptazodisRoute
  '/api/track-view': typeof ApiTrackViewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/lt': typeof LtIndexRoute
  '/admin/analitika': typeof AuthenticatedAdminAnalitikaRoute
  '/admin/sablonai': typeof AuthenticatedAdminSablonaiRoute
  '/admin/uzklausos': typeof AuthenticatedAdminUzklausosRoute
  '/admin/vartotojai': typeof AuthenticatedAdminVartotojaiRoute
  '/lt/blog/$slug': typeof LtBlogSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/lt/blog': typeof LtBlogIndexRoute
  '/admin/perziura/$id': typeof AuthenticatedAdminPerziuraIdRoute
  '/admin/projektai/$id': typeof AuthenticatedAdminProjektaiIdRoute
  '/admin/projektai/nustatymai': typeof AuthenticatedAdminProjektaiNustatymaiRoute
  '/admin/registras/$id': typeof AuthenticatedAdminRegistrasIdRoute
  '/admin/registras/importas': typeof AuthenticatedAdminRegistrasImportasRoute
  '/admin/straipsniai/$id': typeof AuthenticatedAdminStraipsniaiIdRoute
  '/admin/projektai': typeof AuthenticatedAdminProjektaiIndexRoute
  '/admin/registras': typeof AuthenticatedAdminRegistrasIndexRoute
  '/admin/straipsniai': typeof AuthenticatedAdminStraipsniaiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/prisijungimas': typeof PrisijungimasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slaptazodis': typeof SlaptazodisRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/track-view': typeof ApiTrackViewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/lt/': typeof LtIndexRoute
  '/_authenticated/admin/analitika': typeof AuthenticatedAdminAnalitikaRoute
  '/_authenticated/admin/sablonai': typeof AuthenticatedAdminSablonaiRoute
  '/_authenticated/admin/uzklausos': typeof AuthenticatedAdminUzklausosRoute
  '/_authenticated/admin/vartotojai': typeof AuthenticatedAdminVartotojaiRoute
  '/lt/blog/$slug': typeof LtBlogSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/lt/blog/': typeof LtBlogIndexRoute
  '/_authenticated/admin/perziura/$id': typeof AuthenticatedAdminPerziuraIdRoute
  '/_authenticated/admin/projektai/$id': typeof AuthenticatedAdminProjektaiIdRoute
  '/_authenticated/admin/projektai/nustatymai': typeof AuthenticatedAdminProjektaiNustatymaiRoute
  '/_authenticated/admin/registras/$id': typeof AuthenticatedAdminRegistrasIdRoute
  '/_authenticated/admin/registras/importas': typeof AuthenticatedAdminRegistrasImportasRoute
  '/_authenticated/admin/straipsniai/$id': typeof AuthenticatedAdminStraipsniaiIdRoute
  '/_authenticated/admin/projektai/': typeof AuthenticatedAdminProjektaiIndexRoute
  '/_authenticated/admin/registras/': typeof AuthenticatedAdminRegistrasIndexRoute
  '/_authenticated/admin/straipsniai/': typeof AuthenticatedAdminStraipsniaiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prisijungimas'
    | '/sitemap.xml'
    | '/slaptazodis'
    | '/admin'
    | '/api/track-view'
    | '/blog/$slug'
    | '/blog/'
    | '/lt/'
    | '/admin/analitika'
    | '/admin/sablonai'
    | '/admin/uzklausos'
    | '/admin/vartotojai'
    | '/lt/blog/$slug'
    | '/admin/'
    | '/lt/blog/'
    | '/admin/perziura/$id'
    | '/admin/projektai/$id'
    | '/admin/projektai/nustatymai'
    | '/admin/registras/$id'
    | '/admin/registras/importas'
    | '/admin/straipsniai/$id'
    | '/admin/projektai/'
    | '/admin/registras/'
    | '/admin/straipsniai/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prisijungimas'
    | '/sitemap.xml'
    | '/slaptazodis'
    | '/api/track-view'
    | '/blog/$slug'
    | '/blog'
    | '/lt'
    | '/admin/analitika'
    | '/admin/sablonai'
    | '/admin/uzklausos'
    | '/admin/vartotojai'
    | '/lt/blog/$slug'
    | '/admin'
    | '/lt/blog'
    | '/admin/perziura/$id'
    | '/admin/projektai/$id'
    | '/admin/projektai/nustatymai'
    | '/admin/registras/$id'
    | '/admin/registras/importas'
    | '/admin/straipsniai/$id'
    | '/admin/projektai'
    | '/admin/registras'
    | '/admin/straipsniai'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/prisijungimas'
    | '/sitemap.xml'
    | '/slaptazodis'
    | '/_authenticated/admin'
    | '/api/track-view'
    | '/blog/$slug'
    | '/blog/'
    | '/lt/'
    | '/_authenticated/admin/analitika'
    | '/_authenticated/admin/sablonai'
    | '/_authenticated/admin/uzklausos'
    | '/_authenticated/admin/vartotojai'
    | '/lt/blog/$slug'
    | '/_authenticated/admin/'
    | '/lt/blog/'
    | '/_authenticated/admin/perziura/$id'
    | '/_authenticated/admin/projektai/$id'
    | '/_authenticated/admin/projektai/nustatymai'
    | '/_authenticated/admin/registras/$id'
    | '/_authenticated/admin/registras/importas'
    | '/_authenticated/admin/straipsniai/$id'
    | '/_authenticated/admin/projektai/'
    | '/_authenticated/admin/registras/'
    | '/_authenticated/admin/straipsniai/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PrisijungimasRoute: typeof PrisijungimasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SlaptazodisRoute: typeof SlaptazodisRoute
  ApiTrackViewRoute: typeof ApiTrackViewRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  LtIndexRoute: typeof LtIndexRoute
  LtBlogSlugRoute: typeof LtBlogSlugRoute
  LtBlogIndexRoute: typeof LtBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prisijungimas': {
      id: '/prisijungimas'
      path: '/prisijungimas'
      fullPath: '/prisijungimas'
      preLoaderRoute: typeof PrisijungimasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slaptazodis': {
      id: '/slaptazodis'
      path: '/slaptazodis'
      fullPath: '/slaptazodis'
      preLoaderRoute: typeof SlaptazodisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/track-view': {
      id: '/api/track-view'
      path: '/api/track-view'
      fullPath: '/api/track-view'
      preLoaderRoute: typeof ApiTrackViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lt/': {
      id: '/lt/'
      path: '/lt'
      fullPath: '/lt/'
      preLoaderRoute: typeof LtIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analitika': {
      id: '/_authenticated/admin/analitika'
      path: '/analitika'
      fullPath: '/admin/analitika'
      preLoaderRoute: typeof AuthenticatedAdminAnalitikaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sablonai': {
      id: '/_authenticated/admin/sablonai'
      path: '/sablonai'
      fullPath: '/admin/sablonai'
      preLoaderRoute: typeof AuthenticatedAdminSablonaiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/uzklausos': {
      id: '/_authenticated/admin/uzklausos'
      path: '/uzklausos'
      fullPath: '/admin/uzklausos'
      preLoaderRoute: typeof AuthenticatedAdminUzklausosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vartotojai': {
      id: '/_authenticated/admin/vartotojai'
      path: '/vartotojai'
      fullPath: '/admin/vartotojai'
      preLoaderRoute: typeof AuthenticatedAdminVartotojaiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lt/blog/': {
      id: '/lt/blog/'
      path: '/lt/blog'
      fullPath: '/lt/blog/'
      preLoaderRoute: typeof LtBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lt/blog/$slug': {
      id: '/lt/blog/$slug'
      path: '/lt/blog/$slug'
      fullPath: '/lt/blog/$slug'
      preLoaderRoute: typeof LtBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/perziura/$id': {
      id: '/_authenticated/admin/perziura/$id'
      path: '/perziura/$id'
      fullPath: '/admin/perziura/$id'
      preLoaderRoute: typeof AuthenticatedAdminPerziuraIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projektai/': {
      id: '/_authenticated/admin/projektai/'
      path: '/projektai'
      fullPath: '/admin/projektai/'
      preLoaderRoute: typeof AuthenticatedAdminProjektaiIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projektai/$id': {
      id: '/_authenticated/admin/projektai/$id'
      path: '/projektai/$id'
      fullPath: '/admin/projektai/$id'
      preLoaderRoute: typeof AuthenticatedAdminProjektaiIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projektai/nustatymai': {
      id: '/_authenticated/admin/projektai/nustatymai'
      path: '/projektai/nustatymai'
      fullPath: '/admin/projektai/nustatymai'
      preLoaderRoute: typeof AuthenticatedAdminProjektaiNustatymaiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/registras/': {
      id: '/_authenticated/admin/registras/'
      path: '/registras'
      fullPath: '/admin/registras/'
      preLoaderRoute: typeof AuthenticatedAdminRegistrasIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/registras/$id': {
      id: '/_authenticated/admin/registras/$id'
      path: '/registras/$id'
      fullPath: '/admin/registras/$id'
      preLoaderRoute: typeof AuthenticatedAdminRegistrasIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/registras/importas': {
      id: '/_authenticated/admin/registras/importas'
      path: '/registras/importas'
      fullPath: '/admin/registras/importas'
      preLoaderRoute: typeof AuthenticatedAdminRegistrasImportasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/straipsniai/': {
      id: '/_authenticated/admin/straipsniai/'
      path: '/straipsniai'
      fullPath: '/admin/straipsniai/'
      preLoaderRoute: typeof AuthenticatedAdminStraipsniaiIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/straipsniai/$id': {
      id: '/_authenticated/admin/straipsniai/$id'
      path: '/straipsniai/$id'
      fullPath: '/admin/straipsniai/$id'
      preLoaderRoute: typeof AuthenticatedAdminStraipsniaiIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalitikaRoute: typeof AuthenticatedAdminAnalitikaRoute
  AuthenticatedAdminSablonaiRoute: typeof AuthenticatedAdminSablonaiRoute
  AuthenticatedAdminUzklausosRoute: typeof AuthenticatedAdminUzklausosRoute
  AuthenticatedAdminVartotojaiRoute: typeof AuthenticatedAdminVartotojaiRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPerziuraIdRoute: typeof AuthenticatedAdminPerziuraIdRoute
  AuthenticatedAdminProjektaiIdRoute: typeof AuthenticatedAdminProjektaiIdRoute
  AuthenticatedAdminProjektaiNustatymaiRoute: typeof AuthenticatedAdminProjektaiNustatymaiRoute
  AuthenticatedAdminRegistrasIdRoute: typeof AuthenticatedAdminRegistrasIdRoute
  AuthenticatedAdminRegistrasImportasRoute: typeof AuthenticatedAdminRegistrasImportasRoute
  AuthenticatedAdminStraipsniaiIdRoute: typeof AuthenticatedAdminStraipsniaiIdRoute
  AuthenticatedAdminProjektaiIndexRoute: typeof AuthenticatedAdminProjektaiIndexRoute
  AuthenticatedAdminRegistrasIndexRoute: typeof AuthenticatedAdminRegistrasIndexRoute
  AuthenticatedAdminStraipsniaiIndexRoute: typeof AuthenticatedAdminStraipsniaiIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalitikaRoute: AuthenticatedAdminAnalitikaRoute,
  AuthenticatedAdminSablonaiRoute: AuthenticatedAdminSablonaiRoute,
  AuthenticatedAdminUzklausosRoute: AuthenticatedAdminUzklausosRoute,
  AuthenticatedAdminVartotojaiRoute: AuthenticatedAdminVartotojaiRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminPerziuraIdRoute: AuthenticatedAdminPerziuraIdRoute,
  AuthenticatedAdminProjektaiIdRoute: AuthenticatedAdminProjektaiIdRoute,
  AuthenticatedAdminProjektaiNustatymaiRoute:
    AuthenticatedAdminProjektaiNustatymaiRoute,
  AuthenticatedAdminRegistrasIdRoute: AuthenticatedAdminRegistrasIdRoute,
  AuthenticatedAdminRegistrasImportasRoute:
    AuthenticatedAdminRegistrasImportasRoute,
  AuthenticatedAdminStraipsniaiIdRoute: AuthenticatedAdminStraipsniaiIdRoute,
  AuthenticatedAdminProjektaiIndexRoute: AuthenticatedAdminProjektaiIndexRoute,
  AuthenticatedAdminRegistrasIndexRoute: AuthenticatedAdminRegistrasIndexRoute,
  AuthenticatedAdminStraipsniaiIndexRoute:
    AuthenticatedAdminStraipsniaiIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PrisijungimasRoute: PrisijungimasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SlaptazodisRoute: SlaptazodisRoute,
  ApiTrackViewRoute: ApiTrackViewRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  LtIndexRoute: LtIndexRoute,
  LtBlogSlugRoute: LtBlogSlugRoute,
  LtBlogIndexRoute: LtBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
