/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PrisijungimasRouteImport } from './routes/prisijungimas'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as LtIndexRouteImport } from './routes/lt/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminProjektaiRouteImport } from './routes/_authenticated/admin.projektai'
import { Route as AuthenticatedAdminUzklausosRouteImport } from './routes/_authenticated/admin.uzklausos'
import { Route as LtBlogIndexRouteImport } from './routes/lt/blog/index'
import { Route as LtBlogSlugRouteImport } from './routes/lt/blog/$slug'
import { Route as AuthenticatedAdminStraipsniaiIndexRouteImport } from './routes/_authenticated/admin.straipsniai.index'
import { Route as AuthenticatedAdminStraipsniaiIdRouteImport } from './routes/_authenticated/admin.straipsniai.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PrisijungimasRoute = PrisijungimasRouteImport.update({
  id: '/prisijungimas',
  path: '/prisijungimas',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LtIndexRoute = LtIndexRouteImport.update({
  id: '/lt/',
  path: '/lt/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProjektaiRoute =
  AuthenticatedAdminProjektaiRouteImport.update({
    id: '/projektai',
    path: '/projektai',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUzklausosRoute =
  AuthenticatedAdminUzklausosRouteImport.update({
    id: '/uzklausos',
    path: '/uzklausos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LtBlogIndexRoute = LtBlogIndexRouteImport.update({
  id: '/lt/blog/',
  path: '/lt/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LtBlogSlugRoute = LtBlogSlugRouteImport.update({
  id: '/lt/blog/$slug',
  path: '/lt/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminStraipsniaiIndexRoute =
  AuthenticatedAdminStraipsniaiIndexRouteImport.update({
    id: '/straipsniai/',
    path: '/straipsniai/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStraipsniaiIdRoute =
  AuthenticatedAdminStraipsniaiIdRouteImport.update({
    id: '/straipsniai/$id',
    path: '/straipsniai/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prisijungimas': typeof PrisijungimasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/lt/': typeof LtIndexRoute
  '/admin/projektai': typeof AuthenticatedAdminProjektaiRoute
  '/admin/uzklausos': typeof AuthenticatedAdminUzklausosRoute
  '/lt/blog/$slug': typeof LtBlogSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/lt/blog/': typeof LtBlogIndexRoute
  '/admin/straipsniai/$id': typeof AuthenticatedAdminStraipsniaiIdRoute
  '/admin/straipsniai/': typeof AuthenticatedAdminStraipsniaiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prisijungimas': typeof PrisijungimasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/lt': typeof LtIndexRoute
  '/admin/projektai': typeof AuthenticatedAdminProjektaiRoute
  '/admin/uzklausos': typeof AuthenticatedAdminUzklausosRoute
  '/lt/blog/$slug': typeof LtBlogSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/lt/blog': typeof LtBlogIndexRoute
  '/admin/straipsniai/$id': typeof AuthenticatedAdminStraipsniaiIdRoute
  '/admin/straipsniai': typeof AuthenticatedAdminStraipsniaiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/prisijungimas': typeof PrisijungimasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/lt/': typeof LtIndexRoute
  '/_authenticated/admin/projektai': typeof AuthenticatedAdminProjektaiRoute
  '/_authenticated/admin/uzklausos': typeof AuthenticatedAdminUzklausosRoute
  '/lt/blog/$slug': typeof LtBlogSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/lt/blog/': typeof LtBlogIndexRoute
  '/_authenticated/admin/straipsniai/$id': typeof AuthenticatedAdminStraipsniaiIdRoute
  '/_authenticated/admin/straipsniai/': typeof AuthenticatedAdminStraipsniaiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prisijungimas'
    | '/sitemap.xml'
    | '/admin'
    | '/blog/$slug'
    | '/blog/'
    | '/lt/'
    | '/admin/projektai'
    | '/admin/uzklausos'
    | '/lt/blog/$slug'
    | '/admin/'
    | '/lt/blog/'
    | '/admin/straipsniai/$id'
    | '/admin/straipsniai/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prisijungimas'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/blog'
    | '/lt'
    | '/admin/projektai'
    | '/admin/uzklausos'
    | '/lt/blog/$slug'
    | '/admin'
    | '/lt/blog'
    | '/admin/straipsniai/$id'
    | '/admin/straipsniai'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/prisijungimas'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/blog/'
    | '/lt/'
    | '/_authenticated/admin/projektai'
    | '/_authenticated/admin/uzklausos'
    | '/lt/blog/$slug'
    | '/_authenticated/admin/'
    | '/lt/blog/'
    | '/_authenticated/admin/straipsniai/$id'
    | '/_authenticated/admin/straipsniai/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PrisijungimasRoute: typeof PrisijungimasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  LtIndexRoute: typeof LtIndexRoute
  LtBlogSlugRoute: typeof LtBlogSlugRoute
  LtBlogIndexRoute: typeof LtBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prisijungimas': {
      id: '/prisijungimas'
      path: '/prisijungimas'
      fullPath: '/prisijungimas'
      preLoaderRoute: typeof PrisijungimasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lt/': {
      id: '/lt/'
      path: '/lt'
      fullPath: '/lt/'
      preLoaderRoute: typeof LtIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projektai': {
      id: '/_authenticated/admin/projektai'
      path: '/projektai'
      fullPath: '/admin/projektai'
      preLoaderRoute: typeof AuthenticatedAdminProjektaiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/uzklausos': {
      id: '/_authenticated/admin/uzklausos'
      path: '/uzklausos'
      fullPath: '/admin/uzklausos'
      preLoaderRoute: typeof AuthenticatedAdminUzklausosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lt/blog/': {
      id: '/lt/blog/'
      path: '/lt/blog'
      fullPath: '/lt/blog/'
      preLoaderRoute: typeof LtBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lt/blog/$slug': {
      id: '/lt/blog/$slug'
      path: '/lt/blog/$slug'
      fullPath: '/lt/blog/$slug'
      preLoaderRoute: typeof LtBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/straipsniai/': {
      id: '/_authenticated/admin/straipsniai/'
      path: '/straipsniai'
      fullPath: '/admin/straipsniai/'
      preLoaderRoute: typeof AuthenticatedAdminStraipsniaiIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/straipsniai/$id': {
      id: '/_authenticated/admin/straipsniai/$id'
      path: '/straipsniai/$id'
      fullPath: '/admin/straipsniai/$id'
      preLoaderRoute: typeof AuthenticatedAdminStraipsniaiIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminProjektaiRoute: typeof AuthenticatedAdminProjektaiRoute
  AuthenticatedAdminUzklausosRoute: typeof AuthenticatedAdminUzklausosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminStraipsniaiIdRoute: typeof AuthenticatedAdminStraipsniaiIdRoute
  AuthenticatedAdminStraipsniaiIndexRoute: typeof AuthenticatedAdminStraipsniaiIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminProjektaiRoute: AuthenticatedAdminProjektaiRoute,
  AuthenticatedAdminUzklausosRoute: AuthenticatedAdminUzklausosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminStraipsniaiIdRoute: AuthenticatedAdminStraipsniaiIdRoute,
  AuthenticatedAdminStraipsniaiIndexRoute:
    AuthenticatedAdminStraipsniaiIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PrisijungimasRoute: PrisijungimasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  LtIndexRoute: LtIndexRoute,
  LtBlogSlugRoute: LtBlogSlugRoute,
  LtBlogIndexRoute: LtBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
