/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PrisijungimasRouteImport } from './routes/prisijungimas'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as LtIndexRouteImport } from './routes/lt/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUzklausosRouteImport } from './routes/_authenticated/admin.uzklausos'
import { Route as LtBlogIndexRouteImport } from './routes/lt/blog/index'
import { Route as LtBlogSlugRouteImport } from './routes/lt/blog/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PrisijungimasRoute = PrisijungimasRouteImport.update({
  id: '/prisijungimas',
  path: '/prisijungimas',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LtIndexRoute = LtIndexRouteImport.update({
  id: '/lt/',
  path: '/lt/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUzklausosRoute =
  AuthenticatedAdminUzklausosRouteImport.update({
    id: '/admin/uzklausos',
    path: '/admin/uzklausos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LtBlogIndexRoute = LtBlogIndexRouteImport.update({
  id: '/lt/blog/',
  path: '/lt/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LtBlogSlugRoute = LtBlogSlugRouteImport.update({
  id: '/lt/blog/$slug',
  path: '/lt/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prisijungimas': typeof PrisijungimasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/lt/': typeof LtIndexRoute
  '/admin/uzklausos': typeof AuthenticatedAdminUzklausosRoute
  '/lt/blog/$slug': typeof LtBlogSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/lt/blog/': typeof LtBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prisijungimas': typeof PrisijungimasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/lt': typeof LtIndexRoute
  '/admin/uzklausos': typeof AuthenticatedAdminUzklausosRoute
  '/lt/blog/$slug': typeof LtBlogSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/lt/blog': typeof LtBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/prisijungimas': typeof PrisijungimasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/lt/': typeof LtIndexRoute
  '/_authenticated/admin/uzklausos': typeof AuthenticatedAdminUzklausosRoute
  '/lt/blog/$slug': typeof LtBlogSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/lt/blog/': typeof LtBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prisijungimas'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/blog/'
    | '/lt/'
    | '/admin/uzklausos'
    | '/lt/blog/$slug'
    | '/admin/'
    | '/lt/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prisijungimas'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/blog'
    | '/lt'
    | '/admin/uzklausos'
    | '/lt/blog/$slug'
    | '/admin'
    | '/lt/blog'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/prisijungimas'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/blog/'
    | '/lt/'
    | '/_authenticated/admin/uzklausos'
    | '/lt/blog/$slug'
    | '/_authenticated/admin/'
    | '/lt/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PrisijungimasRoute: typeof PrisijungimasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  LtIndexRoute: typeof LtIndexRoute
  LtBlogSlugRoute: typeof LtBlogSlugRoute
  LtBlogIndexRoute: typeof LtBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prisijungimas': {
      id: '/prisijungimas'
      path: '/prisijungimas'
      fullPath: '/prisijungimas'
      preLoaderRoute: typeof PrisijungimasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lt/': {
      id: '/lt/'
      path: '/lt'
      fullPath: '/lt/'
      preLoaderRoute: typeof LtIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/uzklausos': {
      id: '/_authenticated/admin/uzklausos'
      path: '/admin/uzklausos'
      fullPath: '/admin/uzklausos'
      preLoaderRoute: typeof AuthenticatedAdminUzklausosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lt/blog/': {
      id: '/lt/blog/'
      path: '/lt/blog'
      fullPath: '/lt/blog/'
      preLoaderRoute: typeof LtBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lt/blog/$slug': {
      id: '/lt/blog/$slug'
      path: '/lt/blog/$slug'
      fullPath: '/lt/blog/$slug'
      preLoaderRoute: typeof LtBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminUzklausosRoute: typeof AuthenticatedAdminUzklausosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminUzklausosRoute: AuthenticatedAdminUzklausosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PrisijungimasRoute: PrisijungimasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  LtIndexRoute: LtIndexRoute,
  LtBlogSlugRoute: LtBlogSlugRoute,
  LtBlogIndexRoute: LtBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
